### ISSUE TITLE
Language File Update

### ISSUE THREAD

**Issue by Aericio** [jasonwynn10/MyPlot#10]
- [ ] Czech Language
- [ ] Chinese Language (zho.ini)
- [ ] Chinese Language (chs.ini)
- [ ] French Language
- [ ] Dutch (Netherlands) Language
- [ ] Spanish Language
- [ ] Vietnamese Language
- [ ] German Language

**Comment by jasonwynn10** [comment]
look at the multi-lang project...

**Comment by Aericio** [comment]
What multi-lang project :?

**Comment by jasonwynn10** [comment]
Yikes!! we definitely need to update these

**Comment by jasonwynn10** [comment]
https://github.com/jasonwynn10/MyPlot/projects/2#card-321795

**Comment by jasonwynn10** [comment]
we can't use google translate, it's unpredictable for what it outputs...

**Comment by Aericio** [comment]
Mandarin = Chinese. Of course, different speaking but same characters.

**Comment by jasonwynn10** [comment]
what region? different regions use different characters don't they?

**Comment by Aericio** [comment]
Depends if its traditional or simplified. They should know both, so it should be fine.

**Comment by jasonwynn10** [comment]
ok, I'll do french

**Comment by SalmonGER** [comment]
Leave German to me. :)

**Comment by Aericio** [comment]
love ya <3

**Comment by jerryzooyoyo** [comment]
Well, I live in Taiwan.
May I help the Chinese language pack(ROC and PRC)?

**Comment by jasonwynn10** [comment]
sure! We can use all the help we can get!

**Comment by jasonwynn10** [comment]
where are the english grammar errors?

**Comment by Aericio** [comment]
@jerryzooyoyo Definately :D

**Comment by jasonwynn10** [comment]
ima ask@Ad5001 to do french for us because he did it for MyPlot before

**Comment by jasonwynn10** [comment]
This issue will last continuously unless we get a community behind this project. I plan on publishing this plugin to the new PM forums soon

**Comment by MorpheusTP** [comment]
What did you mean @SalmomGER ?
I did also helped!

**Comment by MorpheusTP** [comment]
* @SalmonGER

**Comment by SalmonGER** [comment]
@MorpheusTP ?

**Comment by Aericio** [comment]
@SalmonGER Yo 'Salmom'

**Comment by MorpheusTP** [comment]
@SalmonDE I mean why did you say you should make German alone?

**Comment by SalmonDE** [comment]
@MorpheusTP Lol when did I say that?

**Comment by Aericio** [comment]
@SalmonDE Believe he means when you said "leave german to me"

@MorpheusTP That was before you asked to be translator lol

**Comment by SalmonDE** [comment]
@Aericio Lol. @MorpheusTP Das war mehr als "Überlasst das mir" gemeint. Und das war auch bereits vor sehr vielen Monaten.

**Comment by Driesboy** [comment]
plz add all DUTCH things so i can start
set it in English and i will translate

**Comment by Aericio** [comment]
@Driesboy Fork this and delete the lines in nl.ini and just copy and paste eng.ini into it.

**Comment by jasonwynn10** [comment]
I'm gonna start translating with google next week

**Comment by PikyCZ** [comment]
i can translate czech language :D

**Comment by PikyCZ** [comment]
Czech language is updated!

**Comment by MorpheusTP** [comment]
@SalmonDE Hey, ich weiss das ist schon sehr alt, aber ich habe das nicht richtig gesehen. Von daher also mal ein "Sorry" von meiner Seite aus.  Ich hätte lieber erst mal richtig gucken sollen.

**Comment by SalmonDE** [comment]
@MorpheusTP No worries, I'm not mad. :)

**Comment by jasonwynn10** [comment]
Bump
We really need to get this done asap

**Comment by SalmonDE** [comment]
German file should be ready

**Comment by jasonwynn10** [comment]
Funny... I just found some more things to update 😅

**Comment by PikyCZ** [comment]
jasonwynn10 why you closed czech language update from me?

**Comment by winterbuild7074** [comment]
**More languages:**
- **Portuguese/Brazilian Portuguese**
- **Italian**
- **Russian**
- **Serbian**
- Turkish
- Tagalog
- Japanese
- Hindi
- Irish
- Polish
- Greek
- Arabic
- Thai
- Finnish
- Norwegian
- Swedish
- Icelandic
- Romanian

**Comment by Ad5001** [comment]
I will def do the french lang in a few days. Just the time to finish some stuff...

**Comment by jasonwynn10** [comment]
I'm going to start completing translations with google translate sometime soon

**Comment by kenygamer** [comment]
Spanish language pack was written by me... mark it as [ X ]

**Comment by jasonwynn10** [comment]
Closing because players can use custom messages now

**Comment by kenygamer** [comment]
> Closing because players can use custom messages now

hello again after a while,
that's alright but we should still have a default pack for each language.
