### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Akuroma** [jasonwynn10/MyPlot#100]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
An Error is thrown in console when starting the server.

## Client information
PocketMine-MP Version:  PocketMine-MP 1.7dev 「[REDACTED]」
Plugin Version: API-3
PHP version: 7.0.13 (default)

## Optional information
```
2017-09-25 [17:35:18] [Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "MyPlot-API3/src/MyPlot/MyPlot" at line 441
```

**Comment by OfficialAndii** [comment]
I have the Same Problem ._.
