### ISSUE TITLE
Plugin is not loading.

### ISSUE THREAD

**Issue by OfficialAndii** [jasonwynn10/MyPlot#101]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Plugin is not loading.

## Reproducing the issue
1. DevTools is loading the Folder-Plugin
2. Then comes the Error and the Plugin is at /pl red marked.

## Client information
PocketMine-MP Version: `[17:06:39] [Server thread/INFO]: This server is running PocketMine-MP 1.7dev-82 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.2.0.81 (protocol version 137)
`
Plugin Version: `[17:03:28] [Server thread/INFO]: Enabling MyPlot v1.1.7
`
PHP version: 7.0.13 (default)

## Optional information
`[17:03:28] [Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "MyPlot/src/                                              MyPlot/MyPlot" at line 441
`

**Comment by OfficialAndii** [comment]
Have fixed the Problem. ;)

**Comment by Akuroma** [comment]
How did you fix it?

**Comment by Aromastoffe** [comment]
Wie hast du es behoben?
