### ISSUE TITLE
Spoon Detector?

### ISSUE THREAD

**Issue by VoxCeleste** [jasonwynn10/MyPlot#105]
Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "MyPlot-API3/src/MyPlot/MyPlot" at line 441

**Comment by VoxCeleste** [comment]
i am using the latest pmmp pocketmine build

**Comment by HimbeersaftLP** [comment]
DowNLoaD tHe pLuGiN frOM pOgiT

**Comment by VoxCeleste** [comment]
Th@NkS T0 yOu M4tE!

**Comment by thebigsmileXD** [comment]
Read closed issues + Readme before asking next time: https://github.com/jasonwynn10/MyPlot/issues/69 https://github.com/jasonwynn10/MyPlot/issues/101 https://github.com/jasonwynn10/MyPlot/issues/100 + the issue template should've noticed you about checking issues too
