### ISSUE TITLE
Feature Request: API Extending for Plot bounding boxes and more

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#107]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Optional information
I am working on extending MyPlot to have API commands for plugins like MyPlot, but also to simplify some things.
This issue is more of an announcement, but also a collection of things that MyPlot would need to add

It is planned to add:
- permissions for using we on own plots
- permissions for using we on other persons plots
- permissions for using we on #59 merged plots
- Trying to check if the selection is not to big

**Comment by jasonwynn10** [comment]
This would be better placed in MyPlot Addons. I don't want other plugin involvement which isn't tied to economy in MyPlot

**Comment by thebigsmileXD** [comment]
I thought that would be visible out of the issue description, but here again:

MyPlot will get some extended API code for non-MyPlot plugins.
These will include for example: Getting a proper size of plots (also when combined via plot combining plugin); Permission reading; Translations (might not all be in myplot directly); Probably a config setting

**Comment by jasonwynn10** [comment]
As I previously said, I don’t want non-economy plugin involvement. I will not add permissions or  otherwise to MyPlot that do not pertain the the plugin itself. This would be better done through MyPlot Addons

**Comment by thebigsmileXD** [comment]
As i previousely said: I WILL have to extend MyPlot's API with maybe 2 functions.

**Comment by HimbeersaftLP** [comment]
> I don't want other plugin involvement which isn't tied to economy in MyPlot

Why though?

**Comment by thebigsmileXD** [comment]
@HimbeersaftLP it makes sense to not wanting to include stuff by other plugins.
If they malfunction, the people most likely comment in this issue tracker etc

**Comment by jasonwynn10** [comment]
MyPlot is based on PlotMe, so I want to keep the plugin as close as I can get it to http://plotme.worldcretornica.com/

**Comment by jasonwynn10** [comment]
@thebigsmileXD if you want to use MagicWE with MyPlot, then do like Sandertv did. Don't update MyPlot to use the plugin. Update the Plugin to use MyPlot.

**Comment by thebigsmileXD** [comment]
![image](https://user-images.githubusercontent.com/8733998/31635760-45831aea-b2c8-11e7-86a7-c7c55f334542.png)

**Comment by jasonwynn10** [comment]
What are you defining Plot bounding boxes as?

**Comment by thebigsmileXD** [comment]
API::getPlotBB():AxisAlignedBB -> must work with connected plots, so maybe events etc etc. Streets too.

**Comment by jasonwynn10** [comment]
Plots don't have bounding boxes though because they are not entities or singular blocks

**Comment by thebigsmileXD** [comment]
http://memedad.com/meme/172636

**Comment by HimbeersaftLP** [comment]
> MyPlot is based on PlotMe, so I want to keep the plugin's features to be as close as I can get it too.

Does adding more API make it worse though? No

**Comment by jasonwynn10** [comment]
Not necessarily. I want to keep the features as close as possible, but I never looked at the code for PlotMe, so I am doing the API as it's needed. I want the features to match, but the code can be slightly different. MagicWE can be modified to work with MyPlot, not the other way around. That's my final say on this

**Comment by thebigsmileXD** [comment]
This is exactly what i said before

**Comment by Sandertv** [comment]
Even though it would be a fair idea to add some functions like getMaxX() in plots, it really isn't something mandatory to add. It's very easy to build on My plot with the current API as well. Adding functions like getMinX() will be useful when plots are able to be merged, but that's a next step nobody should currently be bothered about.

**Comment by jasonwynn10** [comment]
AABBs were added. Permissions will not be added to MyPlot for MagicWE. MagicWE can be modified to work with MyPlot, not the other way around

**Comment by thebigsmileXD** [comment]
I stopped supporting outdated plugins
