### ISSUE TITLE
Option to enable changing border + resetting it

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#109]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Due to using old MyPlot worlds, /p reset does not reset the border where users previousely were able to build
Also, not everyone likes stone slab borders

## Reproducing the issue
1. Use old world
2. use /plot reset confirm

## Client information
PocketMine-MP Version: *
Plugin Version: *
PHP version: 7.2 (default)

**Comment by jasonwynn10** [comment]
Slabs are simply the default border. it can easily be changed in the config to another block of choice or air

**Comment by thebigsmileXD** [comment]
You misunderstood: I want players to change the slabs on their own plots

**Comment by jasonwynn10** [comment]
Here's a plugin script that will allow players to change the plot borders. This will hopefully satisfy needs until the branch is merged.

https://gist.github.com/jasonwynn10/69acd21fd4878c502de9651d25b68199

**Comment by GamerDaniel3000** [comment]
Hey Jason
If I release the property then the edge still remains the way I changed it.
Please correct that then the edge resets to the config setting.

**Comment by jasonwynn10** [comment]
The edge should only be reset if it is able to be changed. Since the feature is not currently implemented, it will not be added until the rest of the plot-borders feature is added

**Comment by Jax12344321** [comment]
How do I get that jn a .phar?

**Comment by jasonwynn10** [comment]
download from poggit
