### ISSUE TITLE
/p clear results in bugging in slabs

### ISSUE THREAD

**Issue by Akuroma** [jasonwynn10/MyPlot#110]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Reproducing the issue
1. Claim a random plot
2. Build something
3. use /p clear by standing on the plot

## Client information
PocketMine-MP Version: PocketMine-MP 1.7dev 「[REDACTED]」
Plugin Version: latest version
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
The plot is cleared, but it takes time for the client to update with the block changes.

**Comment by thebigsmileXD** [comment]
I think you did not understand him - You are teleportet INSIDE of slabs and start gliching around (movement)

**Comment by Akuroma** [comment]
Still glitching in slabs.

**Comment by Aericio** [comment]
Doesn't seem to be an issue anymore, you aren't teleported anywhere once you run /p clear or /p reset.

Tested in flight and on ground.
