### ISSUE TITLE
Suggestion: /p info playername

### ISSUE THREAD

**Issue by XDqrkneZ** [jasonwynn10/MyPlot#113]
Just a suggestion. /p info username, shows their plot ID because sometimes players have duplicated items in their plot and don't want to tell their plot ID.

**Comment by jasonwynn10** [comment]
Do you mean the plot's X;Z coordinates?

**Comment by XDqrkneZ** [comment]
yes

**Comment by thebigsmileXD** [comment]
Got the same idea for warping to plots of other people. I am currently playing PC servers where you have /ps h username number as options

**Comment by jasonwynn10** [comment]
Feature Completed in f08b03bdea14344032fe699a4ef1482a03cfb7d9
