### ISSUE TITLE
API 3.0.0Alpha9 not supported

### ISSUE THREAD

**Issue by alexbgameson** [jasonwynn10/MyPlot#114]
Pocketmines API 3.0.0Alpha9 is not supported by your plugin.

Please add plugin compatibility. I will pay you if I have to. 

## Client information
PocketMine-MP Version: 3.0.0Alpha9
Plugin Version: dev-115
PHP version: 7.2

**Comment by jasonwynn10** [comment]
This statement is false. Please check for a more updated build

**Comment by alexbgameson** [comment]
Which branch?

On Oct 25, 2017 7:15 PM, "jasonwynn10" <notifications@github.com> wrote:

Closed #114 <https://github.com/jasonwynn10/MyPlot/issues/114>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jasonwynn10/MyPlot/issues/114#event-1310937360>, or mute
the thread

**Comment by jasonwynn10** [comment]
use the API3 branch
