### ISSUE TITLE
Spoondetector

### ISSUE THREAD

**Issue by Antisa14200** [jasonwynn10/MyPlot#119]
Hi, just a quick question
Where can I get spoondetector and how to set it up?
If there's already solved solution for this, link?

**Comment by Antisa14200** [comment]
I also did downloaded plugin from poggit and didn't get it.

**Comment by Antisa14200** [comment]
Got it, thanks.

**Comment by thebigsmileXD** [comment]
@jasonwynn10 maybe you should clone this:
https://github.com/thebigsmileXD/PocketRadio/issues/2
