### ISSUE TITLE
UpdatePlotLiquids setting doesn't work

### ISSUE THREAD

**Issue by Akuroma** [jasonwynn10/MyPlot#121]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue Description
Restrict Entitymovement is not working. I've set it to false in my config.yml. But water and lava still flows.

## Reproducing the issue
1. set option in config to false and restart
2. claim a plot
3. place water or lava with bucket

## Client information
PocketMine-MP Version: PocketMine-MP 1.7dev-522 「[REDACTED]」
Plugin Version: 1.1.7
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
Water and Lava **blocks** are not **entities**

**Comment by Akuroma** [comment]
I'm sry I meant "UpdatePlotLiquids". But I also set this to "false" and water as well as lava are still flowing.

**Comment by jasonwynn10** [comment]
fixed in 29bb8fe
