### ISSUE TITLE
MyPlot and EconomyAPI

### ISSUE THREAD

**Issue by TheClimbing** [jasonwynn10/MyPlot#123]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
MyPLot fails to substract money from EconomyS player balance

## Reproducing the issue
1. Set up a server with Plots and EconomyAPI
2.Try to /p claim
3.Check out the console 

## Client information
PocketMine-MP Version: PocketMine-MP 1.7dev-579
Plugin Version: 1.2.2
PHP version: 7.2.0 (default)

## Optional information
```
[EconomyAPI] MyPlot failed to reduce money of TheClimbing
```

**Comment by jasonwynn10** [comment]
What version of EconomyAPI are you using? What does your MyPlot config look like? Are there any other plugins installed on the server?

**Comment by TheClimbing** [comment]
`Achieve v1.0.0, AllSigns v1.0.6, AlwaysSpawn v2.2.3-4, CustomAlerts v1.7.2-3, CustomBar v1.0, EconomyAPI v5.7.1-4, EconomyPShop v2.0.2-5, EconomyShop v2.0.8-6, essentialsTP v1.2.0-5, HotBlock v1.0.7, HungerGames vBuild#18.1, iProtector v3.1.0-8, ItemCloud v1.3.0-2, MineReset v3.0.2, NoTell v1.1.2-3, Parkour v1.5.6-4, PlayerJoin v1.0.0, PureEntitiesX v0.2.8-3.dev3, PurePerms v1.4.1-3, RestartMe v1.3.0, RolePlay v1.1.0-3, TeaSpoon v1.0.0, VoteReward v3.0.2-4, Worlds v1.0.13, GrabBag v2.4.0-4, MyPlot v1.2.2, PocketLotto v1.0.1, PureChat v1.4.10-4` These are my plugins and for the myplot config I have use economy set to true if you want the rest i can upload it too

**Comment by TheClimbing** [comment]
Any developments.I tried disabling EconomyAPI related plugins but MyPlot was still unable to subtract money of player

**Comment by jasonwynn10** [comment]
Where did you get your EconomyAPI phar from?
