### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by GageGamesHD** [jasonwynn10/MyPlot#124]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
[04:43:49] [Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "SkyBlockPE-master/src/MyPlot/MyPlot" at line 436

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 
PocketMine-MP 1.7dev-570 「[REDACTED]」 implementing API version 3.0.0-ALPHA10
Plugin Version: 
PHP version: 7.2.0 (default)

## Optional information
```
Put a console error here
```

**Comment by thebigsmileXD** [comment]
![image](https://user-images.githubusercontent.com/8733998/34614797-eedca0a8-f232-11e7-9b7f-1e7f67d5849d.png)
https://tenor.com/view/sure-john-cena-gif-5783187

**Comment by jasonwynn10** [comment]
Clearly, you aren’t using a supported version. Nor an official build from poggit. This issue is invalid

**Comment by thebigsmileXD** [comment]
But hey, i must say, it is totally not a duplicated issue. ;) 

https://github.com/jasonwynn10/MyPlot/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+spoondetector
