### ISSUE TITLE
SpoonDetector error line 441

### ISSUE THREAD

**Issue by jbreadtoasted** [jasonwynn10/MyPlot#125]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
When loading says there is an error with SpoonDetector not found 

## Reproducing the issue
1. ...Starting the server with 1.1.7 verison of plugin using devtools
2. ...

 1.1.7 (plugin) 7.2.0 ocr3 (PHP) PocketMine-MP 1.7dev-600
## Client information
PocketMine-MP Version:   PocketMine-MP 1.7dev-600
Plugin Version: 1.1.7
PHP version: 7.2.0 ocr3 

## https://pastebin.com/vTCVeLw1
```
Put a console error here
```[Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "MyPlot-API3/src/MyPlot/MyPlot" at line 441

**Comment by Aericio** [comment]
https://poggit.pmmp.io/ci/jasonwynn10/MyPlot/MyPlot

Download the .phar here. We use spoondetector to prevent others from using this plugin on other server softwares, and manually downloading the .zip from GitHub does not retrieve these files from the original repository. 

@jasonwynn10 you should add a message if that class isn't found, telling them what's the issue... or put it in the issue template to check off ._.

**Comment by thebigsmileXD** [comment]
https://github.com/jasonwynn10/MyPlot/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+spoondetector
