### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by isoz** [jasonwynn10/MyPlot#126]
Join the game, issue the command /p generate plots, upon teleporting to plots world my windows 10 client crashes, no errors.

Using latest PMMP phar and latest myplot from poggit.

**Comment by Aericio** [comment]
Going to try to reproduce.

**Comment by Aericio** [comment]
Sorry, can you specify which branch's latest build?

**Comment by isoz** [comment]
I got PMMP from jenkins, latest, and MyPlot from poggit latest dev.

**Comment by Aericio** [comment]
I cannot reproduce the error. I'm using the windows 10 client also.

pmmp version: `PocketMine-MP version 1.7dev-625 "[REDACTED]" (API 3.0.0-ALPHA10)`
myplot version: `MyPlot version 1.2.2dev#128`
manyworlds https://github.com/poggit-orphanage/ManyWorlds, manually updated to ALPHA10.

**Comment by jasonwynn10** [comment]
@isoz You didn't follow the issue template, nor did you provide enough information in order to resolve this issue. I am marking this issue as invalid until the template is filled out and all information is given.

**Comment by isoz** [comment]
Could it have something to do with my config?

  # The block that the road is made of (Default is Oak Planks)
  RoadBlock: '5:5'
  # The block that plot walls are made of (Default is Stone Slabs)
  WallBlock: '44:6'
  # The block used as the plot floor (Default is Grass)
  PlotFloorBlock: '251:7'
  # The block that fills the rest of the plot (Default is Dirt)
  PlotFillBlock: '3:0'
  # The block at the bottom (Default is Bedrock)
  BottomBlock: '7:0'

**Comment by jasonwynn10** [comment]
The config appears fine. Please fill out the issue template

**Comment by isoz** [comment]
Yep it was the config, sorry.
