### ISSUE TITLE
Economy

### ISSUE THREAD

**Issue by ElementalMinecraftGaming** [jasonwynn10/MyPlot#129]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
When I loaded the plugin up and went to the plots in-game after setting prices and enabling economy the prices wouldn't show and I couldn't buy a plot. I could only straight up claim one.

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.2.0 (default)

## Optional information
```
No error
```

**Comment by jasonwynn10** [comment]
Did you check your economy account balance after claiming the plot?

**Comment by ElementalMinecraftGaming** [comment]
?
The plots are meant to cost to buy aren't they?
It's meant to show a price whether a player has got money or not right? 
It's meant to cost.
It doesn't even show price animation and when I do /p claim with no money and no op I can still get it free after setting price to $150

**Comment by ElementalMinecraftGaming** [comment]
If there is meant to be rent that doesn't work either.

**Comment by jasonwynn10** [comment]
If MyPlot's config has an economy plugin provided to be used, and the costs are set up correctly, the plugin will charge the player's accounts for claiming, resetting, and clearing plots the way it's supposed to. There are no animations in the process

**Comment by ElementalMinecraftGaming** [comment]
it doesn't work

**Comment by ElementalMinecraftGaming** [comment]
![screenshot 106](https://user-images.githubusercontent.com/20622838/35196106-94751f56-fec5-11e7-8735-e6dc969787b1.png)

I just used /p claim

I was not opped

I have prices at £250

claimed and i only had £2

**Comment by jasonwynn10** [comment]
I recently tested this on my local server. It works as intended.

**Comment by ElementalMinecraftGaming** [comment]
how is that possible? It works for you and not me?

**Comment by jasonwynn10** [comment]
I can only assume you adjusted the config after the world was made right? If so, did you ensure to change the world-specific settings too?

**Comment by ElementalMinecraftGaming** [comment]
world specific? All i did was enable the economy and set the prices, like you are meant to do.

**Comment by jasonwynn10** [comment]
MyPlot is a multi world plugin; therefore, each plot world has different prices and settings. Changing the config will work before a new plot world is made, but if you have a pre-made one, you will need to change it’s world-specific settings in it’s config rather than the plugin config
