### ISSUE TITLE
Claimplots number

### ISSUE THREAD

**Issue by isoz** [jasonwynn10/MyPlot#130]
Permission is set to myplot.claimplots.10, when I try to claim the second plot it says "you reached the limit of 2 plots per player"

Jason, do you still have no access to a computer or internet at home to test your code like a year ago?

And sorry I'm not going to follow the template for something of this simplicity to explain.

**Comment by jasonwynn10** [comment]
That shouldn’t be the case, but I’ll do some testing to see

**Comment by Aericio** [comment]
Can confirm, it sets the plot to max two regardless unless you give the user unlimited/modify the permissions file.

**Comment by jasonwynn10** [comment]
I tested this yesterday and it worked, but I found a small issue with the system and committed 3a405c50c7aa754947de785e0eca50069cfda917
Does it work using the linked commit?

**Comment by thebigsmileXD** [comment]
https://github.com/jasonwynn10/MyPlot/commit/3a405c50c7aa754947de785e0eca50069cfda917#diff-2a8b7cc5077325a7df7e2650d6b7bb53R383 there is the change @ everyone who tries to find changes apart from messed up formatting like double spaces etc

**Comment by jasonwynn10** [comment]
I personally tested this. There are not any issues with permissions in MyPlot.
