### ISSUE TITLE
Add Plot enter and leave events

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#131]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Adding these events would make it easier and more performant for outside plugins to check if:
- a player enters a specific plot, 
- a player may enter a plot
- a plot entered is the own

That way other plugins do not have to check on every onMove if code inside MyPlot replies with anything (example: getPlotAt - a plot or not)

## Optional information
The design could be as follows:
```
__construct(Plugin, Player, Plot)
```

**Comment by jasonwynn10** [comment]
Closing since this was added to the plot-events branch
