### ISSUE TITLE
Water flowing in plots

### ISSUE THREAD

**Issue by isoz** [jasonwynn10/MyPlot#134]
Water flowing is flowing in the plots and going over the plots despite UpdatePlotLiquids being set to false.

---
RestrictEntityMovement: true
UpdatePlotLiquids: false
ClaimPrice: 0
ClearPrice: 0
DisposePrice: 0
ResetPrice: 0
...

This does not happen in the very old outdated version of MyPlot that I still run on my most popular server.

**Comment by thebigsmileXD** [comment]
Reason: it is only restricted on plots, not ways - reproducable by letting water flow from above and make it spread on the border

**Comment by isoz** [comment]
While we're at it, for the love of baby jesus, fix the players getting stuck on the corner of the plot when they teleport, why is this even a thing.

**Comment by jasonwynn10** [comment]
Water flow will only be stopped in the plot areas. Out of plots is always enabled for possible spawn builds

**Comment by isoz** [comment]
I don't know if my english wasn't right, but someone broke an ice block INSIDE their plot and it flowed outside. They were building a mountain with a waterfall...

**Comment by jasonwynn10** [comment]
What does your console look like with debug mode enabled?

**Comment by thebigsmileXD** [comment]
Exactly as normal.

@jasonwynn10 Please re-read the first 2 comments and test it yourself.

**Comment by Aericio** [comment]
Can confirm with isoz, that happens on my server sometimes.

**Comment by isoz** [comment]
Regardless if UpdatePlotLiquids is set to false, things still flow naturally.

**Comment by jasonwynn10** [comment]
This issue was fixed in the marked commit
