### ISSUE TITLE
plugin gets disabled upon server start

### ISSUE THREAD

**Issue by mote166** [jasonwynn10/MyPlot#136]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
as the title says the plugin gets disabled when the server starts , tried removing sqlite3 and mysql from the plugin.yml and only kept yaml and the error got replaced with the spoon detector issue and the plugin got disabled aswell ( tried both zip and phar from poggit they all have the same issue)

## Reproducing the issue
1. ... install php 7.2 from pocketmine binary 
2. ... use the plugin (lol)

## Client information
PocketMine-MP Version:  PocketMine-MP 1.7dev-516 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)
Plugin Version: tried dev-148 and dev-144 from api3 branch both have the same issue
PHP version: 7.2.0 (default)

## Optional information
```
 [Server thread/ERROR]: Required extension sqlite3 not loaded
[02:02:51] [Server thread/CRITICAL]: Could not load plugin 'MyPlot'
```

**Comment by jasonwynn10** [comment]
You didn't enable SQLite3 in your php binary

**Comment by mote166** [comment]
How can i enable it?

**Comment by jasonwynn10** [comment]
Try looking on the forums. There have been A LOT of people who posted issues about this https://forums.pmmp.io/search/7995618/?q=SQLite3+not+found&o=date
