### ISSUE TITLE
/p addhelper "user name" allows name to have spaces.

### ISSUE THREAD

**Issue by Aericio** [jasonwynn10/MyPlot#140]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
If you use quotations around the user's name, it allows the plot owner to type names with spaces in them. I noticed this when flying through my server, seeing a plot with spaces in the helper. It certainly isn't two names- there would be a comma if that was the case. I looked at the table with the SQL database, and there didn't seem to be any sneaky characters. I then tried to use " " around a name with spaces in it, thinking that it could've been because of strings. (correct term?) It added a helper with spaces.

## Reproducing the issue
1. Start the server with MyPlot installed.
2. Claim a plot.
3. Add a helper with " " around the name, but add a space somewhere in that name. ex: "Jason is Awesome"
4. Check /p i, there will be a name with spaces.

## Client information
PocketMine-MP Version: `dev1.7-699` (shouldn't matter)
Plugin Version: `1.1.9`
PHP version: `7.2.1`

## Image Proof
![image](https://user-images.githubusercontent.com/16523741/36950780-03c77a76-1f9f-11e8-83f8-4689a139c811.png)
(no sql modification trickery.)

**Comment by Sandertv** [comment]
Why is that an issue though? The parsing of strings enclosed in `""` is done in PocketMine, it's expected behaviour 😛

**Comment by Aericio** [comment]
uwu ok then didn't know that.
