### ISSUE TITLE
Everyone can edit signs

### ISSUE THREAD

**Issue by isoz** [jasonwynn10/MyPlot#141]
Everyone can edit signs if they hit it and place another sign on top fast regardless of the plot they're on.
Tested on two different servers.

![image](https://user-images.githubusercontent.com/6126350/37049958-7ab97a5e-216a-11e8-8f95-51cc8ab1a78b.png)

**Comment by jasonwynn10** [comment]
That’s not an issue with MyPlot, but it is for PocketMine itself. I’ll see if there’s a workaround I can use
