### ISSUE TITLE
"Plugin Disabled"

### ISSUE THREAD

**Issue by ALearnPro** [jasonwynn10/MyPlot#143]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have? I load the plugin, the file folder is created, but every time I try to use commands, it says "plugin disabled." There is no proper documentation explaining how to configure and set up the plugin and I don't know what to do from here.

## Reproducing the issue
1. ... Install plugin
2. ... Try to run commands

## Client information
PocketMine-MP Version: 1.2.12 API 3-alpha 11
Plugin Version: 1.2.3
PHP version: 7.2.1 (default)

## Optional information
```
Put a console error here
```

**Comment by ALearnPro** [comment]
I don't understand what the unsupported custom installation is. Can you please elaborate and point me in the right direction so I can fix it? I downloaded directly from poggit (where it was approved), and am using PMMP.

**Comment by ALearnPro** [comment]
Ok, thank you so much!

**Comment by ALearnPro** [comment]
29.03 15:50:12 [Server] Server thread/INFO This plugin is disabled
29.03 15:50:12 [Multicraft] CMiko12 ran command: p help
29.03 15:49:17 [Multicraft] Skipped 46 lines due to rate limit (30/s)
29.03 15:48:39 [Server] Startup Done (0.245s)! For help, type "help" or "?"
29.03 15:48:39 [Server] 888 8888888888 888        888       888    888 888    888
29.03 15:48:39 [Server] 888   888P "Y88b d88   888  888        888       888    888 888    888
29.03 15:48:39 [Server] 888   888d888b.   d8P  888  8888888    8888888   888    888 888    888
29.03 15:48:39 [Server] d8P 888  888        888       888    888 888    888
29.03 15:48:39 [Server] 888   d88P  Y88b    d8P888  888        888       d88P  Y88b d88P  Y88b
29.03 15:48:39 [Server] Server thread/NOTICE PurePerms by 64FF00 & ProjectInfinity! #LEET.CC
29.03 15:48:39 [Server] Server thread/INFO Loading PurePerms v1.4.1-4
29.03 15:48:39 [Server] Server thread/INFO Loading Festival v1.0.2-11
29.03 15:48:39 [Server] Server thread/INFO Loading BadWordBlocker v1.1.0
29.03 15:48:39 [Server] Server thread/INFO Loading AllSigns v1.0.7
29.03 15:48:39 [Server] Server thread/INFO Loading BasicHUD v1.0.6-4
29.03 15:48:39 [Server] Server thread/INFO 時刻を Asia/Tokyo に合わせました。
29.03 15:48:39 [Server] Server thread/INFO Loading timeSetter v1.1.0
29.03 15:48:39 [Server] Server thread/INFO Loading EssentialsPE v2.0.0
29.03 15:48:39 [Server] Server thread/INFO Loading resource packs...
29.03 15:48:39 [Server] Server thread/INFO Loading recipes...
29.03 15:48:39 [Server] Server thread/INFO PocketMine-MP [#40b995a 2018-03-10] is distributed under the LGPL License
29.03 15:48:39 [Server] Server thread/INFO This server is running PocketMine-MP [#40b995a 2018-03-10] version 1.7dev "[REDACTED]" (API 3.0.0-ALPHA11)
29.03 15:48:39 [Server] Server thread/INFO Opening server on 45.35.44.138:25650
29.03 15:48:39 [Server] Server thread/NOTICE To disable authentication, set "xbox-auth" to "false" in server.properties.
29.03 15:48:39 [Server] Server thread/NOTICE Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
29.03 15:48:39 [Server] Server thread/INFO Starting Minecraft: PE server version v1.2.10
29.03 15:48:39 [Server] Server thread/INFO Selected English (eng) as the base language
29.03 15:48:39 [Server] Server thread/INFO Loading server properties...
29.03 15:48:39 [Server] Server thread/INFO Loading pocketmine.yml...
29.03 15:48:39 [Server] INFO Launching mod. Please be patient...
29.03 15:48:39 [Multicraft] Failed to copy jarfile from global JAR directory
29.03 15:48:39 [Multicraft] JAR file not found, copying from global JAR directory
29.03 15:48:39 [Multicraft] Failed to create local JAR directory
29.03 15:48:39 [Multicraft] Loaded config for "_Minecraft Pocket% PocketMine-MP PMMP% MCPE 1.2.10 - API 3.0.0-alpha11 (Auto Update)% MCPE v1.2.10 alpha11% 192% <a href="https://github.com/pmmp/PocketMine-MP">PocketMine-MP PMMP</a> is the Official PocketMine-MP software, now back in action with regular updates!<br><br><font color="Red">WARNING: API 3.0.0-ALPHA7+ WILL BREAK MANY PLUGINS!!</font><br \><br \>This pack includes EssentialsPE and PureEntitiesX, both updated for alpha11 changes.<br \><br \><font size="+1" color="#08C0FC"><b>AUTOMATIC Update!<b></font><br>Just restart your server to activate the latest VG tested build."
29.03 15:48:39 [Multicraft] Starting server!

**Comment by jasonwynn10** [comment]
Does the plugin appear green when you do `/plugins`?

**Comment by ALearnPro** [comment]
It lists it as a plugin, but appears red

**Comment by jasonwynn10** [comment]
It looks like multicraft is hiding the issue. I can't help you.

**Comment by ALearnPro** [comment]
Thanks for trying. On a side note, would you be open to me commissioning you to write some plugins for me?
