### ISSUE TITLE
SQLite 3 error

### ISSUE THREAD

**Issue by Xelcronia** [jasonwynn10/MyPlot#15]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Unable to prepare statement, no such column: 'denied' in table 'plots' 

## Reproducing the issue
Put the plugin and restart. (latest master)

## Client information
OS: Ubuntu 15 64bit
PHP: 7.0.4
Server build: Genisys 

## Optional information
[09:59:58] [Server thread/INFO]: [MyPlot] Loading MyPlot

Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied in phar:///home/xel/plugins/phar_MyPlot-master (1)_NeEAyyGMe4f5mMo.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 34

Warning: SQLite3::prepare(): Unable to prepare statement: 1, table plots has no column named denied in phar:///home/xel/plugins/phar_MyPlot-master (1)_NeEAyyGMe4f5mMo.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 39

Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied in phar:///home/xel/plugins/phar_MyPlot-master (1)_NeEAyyGMe4f5mMo.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 42

**Comment by jasonwynn10** [comment]
is there a crash dump file or a console output?

**Comment by Xelcronia** [comment]
Omg I'm so sorry! I totally forgot about it :( 

[09:59:58] [Server thread/INFO]: [MyPlot] Loading MyPlot

Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied in phar:///home/xel/plugins/phar_MyPlot-master (1)_NeEAyyGMe4f5mMo.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 34

Warning: SQLite3::prepare(): Unable to prepare statement: 1, table plots has no column named denied in phar:///home/xel/plugins/phar_MyPlot-master (1)_NeEAyyGMe4f5mMo.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 39

Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied in phar:///home/xel/plugins/phar_MyPlot-master (1)_NeEAyyGMe4f5mMo.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 42

**Comment by jasonwynn10** [comment]
that is an indication that you updated to the new version alright... I forgot to make a function to add the denied players column to the sql table :laughing:
I'm working on it now

**Comment by Xelcronia** [comment]
Question. Would it work for 0.16? cuz the old plots plugin only works for ops.

**Comment by jasonwynn10** [comment]
The latest release of the plugin should allow commands for the players with the appropriate permissions

**Comment by Xelcronia** [comment]
Okay. I'll check it out when you finish working on teh function :D

**Comment by jasonwynn10** [comment]
A temporary fix for this issue would be to manually add the denied column to the database with a sqlite3 editor

**Comment by Xelcronia** [comment]
I have no idea how to do that.

**Comment by jasonwynn10** [comment]
you could also just delete the plots.db file if you need it for a server immediately, but that would delete the plot world data with it and you would need to make a new world

**Comment by Xelcronia** [comment]
Yeah. I could do that!

**Comment by Xelcronia** [comment]
It works! But when I enter a plot, it lags for like 2-3 seconds and shows the popup.

**Comment by jasonwynn10** [comment]
It only lags because it's doing a lot of math and attempting to get screen size data from the player's game. the error was from the generate command I think.

**Comment by Xelcronia** [comment]
After a little observation, I found out the notice appears when a player claims a plot.

**Comment by jasonwynn10** [comment]
not only then, and I thought i fixed it when I was messing with the tasks too. It's just odd
