### ISSUE TITLE
SQLite3 missing column on update

### ISSUE THREAD

**Issue by Tolo0** [jasonwynn10/MyPlot#16]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
SQLite3 error: missing denied column

## Reproducing the issue
{Type something here}

## Client information
{Type something here}

## Optional information
`Version: MyPlot v1.0.13
Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied in phar:///home/tolo/mc2/plugins/MyPlot_v1.0.13.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 34
Warning: SQLite3::prepare(): Unable to prepare statement: 1, table plots has no column named denied in phar:///home/tolo/mc2/plugins/MyPlot_v1.0.13.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 39
Warning: SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied in phar:///home/tolo/mc2/plugins/MyPlot_v1.0.13.phar/src/MyPlot/provider/SQLiteDataProvider.php on line 42
CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'MyPlot v1.0.13': Call to a member function bindValue() on boolean on MyPlot\EventListener
[19:00:19] [Server thread/CRITICAL]: Error: "Call to a member function bindValue() on boolean" (EXCEPTION) in "/plugins/MyPlot_v1.0.13.phar/src/MyPlot/provider/SQLiteDataProvider" at line 116`

**Comment by jasonwynn10** [comment]
there is an issue template for a reason...

**Comment by Tolo0** [comment]
i have to delete the "plots.db" and then reboot?

**Comment by jasonwynn10** [comment]
That should fix it,but you will need to make a new world if the file is deleted

**Comment by Tolo0** [comment]
Is they any other way i can fix it? my plot world is full lol

**Comment by Aericio** [comment]
What? .db file changed? **╯°□°）╯︵ ┻━┻** now I also have to reset my plot world if I choose to use this version. yay time to rebuild another plot spawn.

**Comment by Tolo0** [comment]
u can copy paste with world edit. i have 100s of players plots that il have to delete.  they won't be happy lol

**Comment by jasonwynn10** [comment]
the other method is to modify the db file to have a new 'denied' column set to TEXT

**Comment by jasonwynn10** [comment]
fixed in 77ae10b ?

**Comment by Aericio** [comment]
@Tolo0 I'd only copy and paste the spawn... but some parts are cut off because ayy love you glitched chunks. My plots are around 45 rows and its 90x90 per plot... so there's a lot of stuff on it. Yup, they definitely won't be happy with me resetting, so I let my friend reset it so I don't feel bad.

**Comment by jasonwynn10** [comment]
it only needs reset until the updater is finished

**Comment by Aericio** [comment]
@jasonwynn10 oh good.

**Comment by jasonwynn10** [comment]
@Tolo0 As a temporary fix, post the db file here. Icn edit it and sendit back for the server to work again.

**Comment by Tolo0** [comment]
@jasonwynn10 its ok iv deleted it now lol il just wait for the final update thanks anyway 😊
