### ISSUE TITLE
players can hit entities on other plots

### ISSUE THREAD

**Issue by HGHD-Developer** [jasonwynn10/MyPlot#160]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Players can hit entities on other plots, like playerhead entities
You can hit entities on others Plots

## Client information
Plugin Version: Latest Myplot
PHP version: 7.2.1 (default)
Software: Altay Turanic

## Optional information

You can fix it with adding a new permission

```
no console error!
```
thanks for help :D

**Comment by Aericio** [comment]
You can just use another plugin to disable entity damage on MyPlot worlds. I don’t see a need for MyPlot to implement this, unnecessary.

**Comment by HGHD-Developer** [comment]
@Aericio  wich plugin?

**Comment by Aericio** [comment]
Look for it yourself.
