### ISSUE TITLE
 MyPlot is not working, what should I do?

### ISSUE THREAD

**Issue by DerGamerHD100** [jasonwynn10/MyPlot#162]

**Comment by jasonwynn10** [comment]
I cant help you without knowing the issue

**Comment by DerGamerHD100** [comment]
[Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "MyPlot-master/src/MyPlot/MyPlot" at line 555
??? Can you help me?

**Comment by jasonwynn10** [comment]
you didnt get the plugin from poggit

**Comment by DerGamerHD100** [comment]
I have the plugin on it https://poggit.pmmp.io/ci/Falkirks/spoondetector/spoondetector and also devirion but it still does not work?

**Comment by jasonwynn10** [comment]
I meant MyPlot. you didn't get Myplot from poggit

**Comment by DerGamerHD100** [comment]
But myplot only has it on it does not work

**Comment by jasonwynn10** [comment]
MyPlot 1.2.5 is fully functional with PocketMine build 1001
https://poggit.pmmp.io/p/MyPlot/1.2.5
https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-1001

**Comment by DerGamerHD100** [comment]
my server is running This server is running PocketMine-MP 1.7dev-1076

**Comment by jasonwynn10** [comment]
then I cannot help you. that version is still in development and is not supported

**Comment by DerGamerHD100** [comment]
So I need the outdated PocketMine version?

**Comment by jasonwynn10** [comment]
It's not outdated. it's the latest **released** version. and yes, you will

**Comment by HGHD-Developer** [comment]
@DerGamerHD100  
remove on line 33: use spoondetector\SpoonDetector;
remove on lines: 556-559: SpoonDetector::printSpoon($this, "spoon.txt");
		if($this->isDisabled()) {
			return;
		}

then it should be work!
