### ISSUE TITLE
Heres the information

### ISSUE THREAD

**Issue by Shelly7w7** [jasonwynn10/MyPlot#167]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
Whenever i type /p or /plot nothing popups up

## Reproducing the issue
1. ... Using new api
2. ... New build from poggit

## Client information
PocketMine-MP Version: 
Plugin Version: 1.2.6
PHP version: 7.2.1 (default)
Build: newest release on github by pmmp

## Optional information
```
Put a console error here
```no issue but "thread/INFO Loading MyPlot v1.2.6"

**Comment by jasonwynn10** [comment]
Is that all the console information there is? do you have debug enabled on your server?
