### ISSUE TITLE
SQlite Provider

### ISSUE THREAD

**Issue by Ninib1** [jasonwynn10/MyPlot#168]
Hello,
I cant really speak/write english so i do it fast ^^

language: eng

# The data provider where plot data is stored.
# Current providers are: sqlite, mysql, json, and yaml.
DataProvider: mysql

# contains settings for mysql provider to use when selected
MySQLSettings:
  Host: 127.0.0.1
  Port: 3306
  Username:HIDDEN
  Password: HIDDEN
  DatabaseName: MyPlot
  ShutdownOnFailure: false

# Use an economy with MyPlot. This will allow for plot pricing such as claiming, clearing, etc.
# Currently supported economy plugins: Economy$, PocketMoney, EssentialsPE, EconomyPlus
# Be sure not to use more than 1 economy plugin!
UseEconomy: false

# Amount of plots to be cached.
# Increasing this number will improve performance, but also increase memory usage.
PlotCacheSize: 256

# When a player enters a plot, a popup with basic info will be shown
ShowPlotPopup: true

# Amount of blocks to reset per tick.
# Increasing this number will speed up '/p clear' and '/p reset' but also increases lag
ClearBlocksPerTick: 256

# These settings will be used when creating a new world with the default generator.
DefaultWorld:

  # Restrict entities (e.g. tnt) from moving except falling
  # This will prevent things like tnt cannons from ruining other plots
  RestrictEntityMovement: true

  # Update liquids (e.g. Water) from updating and moving
  # This will allow things like water to lag the server in plot worlds
  UpdatePlotLiquids: false

  # How much it costs to claim a plot (Economy must be set to 'true')
  ClaimPrice: 0
  # How much it costs to clear a plot (Economy must be set to 'true')
  ClearPrice: 0
  # How much it costs to dispose a plot (Economy must be set to 'true')
  DisposePrice: 0
  # How much it costs to reset a plot (Economy must be set to 'true')
  ResetPrice: 0

  # The size of a plot
  PlotSize: 32
  # The height of a plot
  GroundHeight: 64
  # The width of the road
  RoadWidth: 7

  # The block that the road is made of (Default is Oak Planks)
  RoadBlock: '5:0'
  # The block that plot walls are made of (Default is Stone Slabs)
  WallBlock: '44:0'
  # The block used as the plot floor (Default is Grass)
  PlotFloorBlock: '2:0'
  # The block that fills the rest of the plot (Default is Dirt)
  PlotFillBlock: '3:0'
  # The block at the bottom (Default is Bedrock)
  BottomBlock: '7:0'

and why i got this error:
Required extension sqlite3 not loaded

Please Help me

**Comment by Aericio** [comment]
>Required extension sqlite3 not loaded

open bin ->php -> php.ini.

uncomment `;extension=php_mysqli.dll` by removing `;`

should look like `extension=php_mysqli.dll` after.
