### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by treehousemc1** [jasonwynn10/MyPlot#169]
when i do /plot auto it crash my game (not server)

**Comment by Aericio** [comment]
Are there any errors? Try enabling debug.

**Comment by treehousemc1** [comment]
Come my server and try?
no errors in console
ip: mc.happype.us.to  19132

**Comment by treehousemc1** [comment]
Join my server and do /plot auto and you will crash please help. No errors show in console

**Comment by jasonwynn10** [comment]
Fill out the issue template with the required information. THEN we will help you
