### ISSUE TITLE
The "/p done" cmd causing errors

### ISSUE THREAD

**Issue by ChrisNML** [jasonwynn10/MyPlot#17]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
When running the command "/p done" from in game the following error desolate in the console

`[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\level\particle\HappyVillagerParticle::__construct() must be an instance of pocketmine\math\Vector3, boolean given, called in src\MyPlot\task\DoneMarkTask.php on line 27" (EXCEPTION) in "/src/pocketmine/level/particle/HappyVillagerParticle" at line 27`

## Reproducing the issue

Join a server
Claim a plot
Run the command "/p done"
Look at console, error will show

## Client information

Operating system Linux, PHP version: 7.0.9, Server Genisys-unsupported-b6cec51 (0.16)

## Optional information
{Type something here}

**Comment by jasonwynn10** [comment]
I think that command isn't really needed anyway...
