### ISSUE TITLE
CRASH GAME (NOT SERVER)

### ISSUE THREAD

**Issue by treehousemc1** [jasonwynn10/MyPlot#170]
- [] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?

## Reproducing the issue
1. when players do /plot auto  their game crash (not server)
2. ...

## Client information
PocketMine-MP Version: pocketmine 1.7dev-1001
Plugin Version: 1.2.5
PHP version: 7.2.1 (default)

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```
no errors

**Comment by treehousemc1** [comment]
After teleport then crash.  world done Preparing

**Comment by jasonwynn10** [comment]
are you teleporting into a loaded chunk?

**Comment by treehousemc1** [comment]
hmm i guess yes. maybe u can join my server and try it?

**Comment by jasonwynn10** [comment]
Does the crash only happen when this plugin teleports the player in the plot world or can you use the teleport command to go to the same place?

**Comment by treehousemc1** [comment]
When player going plot world it doesnt crash. But when they do /plot auto it does im not sure about about teleport command because i dont know the location.

**Comment by jasonwynn10** [comment]
ok. once you test the teleport command, then I might be able to help you.

**Comment by treehousemc1** [comment]
But how do i know the location

**Comment by jasonwynn10** [comment]
I don't know. You will have to figure it out. also try `/p warp 0;0`

**Comment by treehousemc1** [comment]
ok

**Comment by treehousemc1** [comment]
Can you join? so you will see

**Comment by jasonwynn10** [comment]
No. I don't join servers. The issue you have is not an issue coming from this plugin. It's from PocketMine. I recommend you ask the pmmp forums for help. https://forums.pmmp.io
