### ISSUE TITLE
 Error: "Class 'pocketmine\level\generator\GeneratorManager' not found

### ISSUE THREAD

**Issue by MCPETRTeam** [jasonwynn10/MyPlot#171]
Error: "Class 'pocketmine\level\generator\GeneratorManager' not found" (EXCEPTION) in "MyPlot-master/src/MyPlot/MyPlot" at line 518

## Client information
PocketMine-MP Version:  PocketMine-MP version 1.7dev-1001 "[REDACTED]" (API 3.0.0-ALPHA12)
Plugin Version: 1.2.6
PHP version: 7.2.1 (default)

**Comment by jasonwynn10** [comment]
MyPlot 1.2.6 only works with API3 or higher
