### ISSUE TITLE
Error: "Class 'pocketmine\level\generator\GeneratorManager' not found" (EXCEPTION) in "MyPlot.phar/src/MyPlot/MyPlot" at line 518

### ISSUE THREAD

**Issue by Gtafgu** [jasonwynn10/MyPlot#172]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.2.1 (default)

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by Gtafgu** [comment]
Error: "Class 'pocketmine\level\generator\GeneratorManager' not found" (EXCEPTION) in "MyPlot.phar/src/MyPlot/MyPlot" at line 518

**Comment by jasonwynn10** [comment]
fill out the issue template
