### ISSUE TITLE
Number of Plots able to Claim

### ISSUE THREAD

**Issue by kiingjulz** [jasonwynn10/MyPlot#173]
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
If some servers for instance like mine do not use Economy as an option, could we please have a setting where we can control the amount of plots users can claim?

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.2.1 (default)

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by MSG100TC** [comment]
myplot.claimplots.<plots> |  Allow player to claim <plots> plots
or
myplot.claimplots.unlimited  | Allow player to claim unlimited amount of plots
