### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by MrJhon2** [jasonwynn10/MyPlot#175]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
Hello, I would like to know if there is any way to activate the water in the plots without bugs or without it to cross the limit of the line of the plot, not to go to the street, but wanted this for the API 2.0.0

## Reproducing the issue
1. A água ultrapassa a linha dos plots
2. ...

## Client information
PocketMine-MP Version:  2.0.0
Plugin Version: 1.2.4
PHP version: 7.2.1 (default)

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by Aericio** [comment]
We won't downgrade the current plugin just for you. Try Legacy branch.

**Comment by Aericio** [comment]
or invalid outdated build, eh same same.
