### ISSUE TITLE
p denyplayer not working [UPDATED]

### ISSUE THREAD

**Issue by Crypt97** [jasonwynn10/MyPlot#178]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?

DenyPlayer no ban players to plots

## Reproducing the issue
1. p claim plot
2. p denyplayer xy

## Client information
PocketMine-MP Version: 
Plugin Version: 1.2.6
PHP version: 7.2.6

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by jasonwynn10** [comment]
tested with debug level 2?

**Comment by Crypt97** [comment]
![image](https://user-images.githubusercontent.com/28710769/43422911-5e6e49d4-944b-11e8-901a-b5a767fe16d0.png)

**Comment by Crypt97** [comment]
fork PMMP

**Comment by Crypt97** [comment]
but this has long been no working

**Comment by jasonwynn10** [comment]
no console errors in debug mode?

**Comment by Crypt97** [comment]
no console errors

**Comment by jasonwynn10** [comment]
code looks good and it works for me. How are you testing it?

**Comment by Crypt97** [comment]
come on my server and watch okay? :D

**Comment by Crypt97** [comment]
oh wait no 1.2.6 myplot XD

**Comment by Crypt97** [comment]
my plot version 1.2.3 and now plugin 1.3.3 :o

**Comment by Aericio** [comment]
Oops, there was a build in reference to this: https://github.com/jasonwynn10/MyPlot/commit/5464c8a5bbabf20fb13d84e92f422c70afb9d789.

**Comment by Crypt97** [comment]
I updated the plugin and not good! :/

**Comment by Aericio** [comment]
It would be a different issue then. Create a new issue and provide us with more information.
