### ISSUE TITLE
0.16 Notice

### ISSUE THREAD

**Issue by Adam1609** [jasonwynn10/MyPlot#18]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

Since updating to 0.16.0, I couldn't use any of plot command
## Issue description
Since updating to 0.16.0, I couldn't use any of plot command

## Reproducing the issue
{Type something here}

## Client information
Server is using Elywing 0.16 Stable API 2.0.0
Server OS: Windows Server 2012 R2 64-bit

## Optional information
{Type something here}

**Comment by jasonwynn10** [comment]
what version of the myplot plugin are you using?

**Comment by Adam1609** [comment]
I use older version

**Comment by jasonwynn10** [comment]
That isn't enough info for me to help you
