### ISSUE TITLE
PVP should be disabled on the roads without interfering with plot settings

### ISSUE THREAD

**Issue by Akuroma** [jasonwynn10/MyPlot#181]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
If you deactivate PVP on your own plot it works. But anyway you can pvp on the road. It would be better if the pvp on the road is always deactivated and pvp on the plots is always activated unless you deactivate it by yourself.

## Reproducing the issue
1. Enable PVP in your Plot-World
2. Try hitting people without OP on your plot. (Shouldn't work)
3. Move to the road and try hitting people. (Should work)

## Client information
PocketMine-MP Version: PocketMine-MP 3.1.2
Plugin Version: 1.3.6
PHP version: 7.2.1

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by jasonwynn10** [comment]
This is more of a recommended change. If enough people complain about it, then I will change it. Otherwise, I think the feature is good how it is

**Comment by Aericio** [comment]
If you don't want PvP in your plot, why have it enabled at all? Is there a real purpose for this?
