### ISSUE TITLE
Biome issues

### ISSUE THREAD

**Issue by nikipuh** [jasonwynn10/MyPlot#182]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
If I use "/p biome <biome>" it says biome changed to unknown, the plot id changes (wtf xD) and the biome is still not changed. (Console error below.)

## Reproducing the issue
1. Use /p biome <biome> in your plot

## Client information
PocketMine-MP Version: 3.1.2 for Minecraft: PE v1.5.0 (protocol version 274)
Plugin Version:  1.3.6
PHP version: 7.2.1 (default)

## Optional information
```
[13:59:11] [Server thread/CRITICAL]: Unbehandelter Fehler beim Ausführen des Kommandos 'cb biome plains' in citybuild: Illegal string offset:  -456

[13:59:11] [Server thread/CRITICAL]: ErrorException: "Illegal string offset: -456" (EXCEPTION) in "src/pocketmine/level/format/Chunk" at line 463
```

**Comment by Aericio** [comment]
oh crap, wrong issue >_<

**Comment by Aericio** [comment]
Issue could not be reproduced. Closing.
