### ISSUE TITLE
MyPlot do not work in the 1.5.x MCBEserver

### ISSUE THREAD

**Issue by jackjoe84288** [jasonwynn10/MyPlot#184]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
This plugin ''MyPlot''cannot work in MCBE 1.5.3's server. By the way, my server cor is PPMP src1386.

## Reproducing the issue
1. install the plugin and start the server
2. next,system shows "cannot load" and shutdown the plugin

## Client information
PocketMine-MP Version:PocketMine-MP 3.1.4 for Minecraft: PE v1.5.x (protocol version 274)
Plugin Version: 
PHP version: 7.2.1 (default)

<!-- OPTIONAL INFORMATION - use this section for posting crash dumps, backtraces or other files(please use code markdown!) --
ErrorException: "SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied" (EXCEPTION) in "plugins/MyPlot-master/src/MyPlot/provider/SQLiteDataProvider" at line 32
2018-08-21 [04:50:19] [Server thread/DEBUG]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string SQLite3::prepare(): Unable to prepare statement: 1, no such column: denied, string /home/frog/mcpe/plugins/MyPlot-master/src/MyPlot/provider/SQLiteDataProvider.php, integer 32, array Array())
![received_467244447089739]
(https://user-images.githubusercontent.com/23036635/44405018-ddcbf000-a58a-11e8-8d06-f7fa8ab52b92.jpeg)

**Comment by jasonwynn10** [comment]
You have not provided enough information on your issue. Please specify your problem

**Comment by jackjoe84288** [comment]
Modified and attached to relevant documents

**Comment by jasonwynn10** [comment]
can you show what it says in debug mode?

**Comment by jackjoe84288** [comment]
No, it can't be opened and read at all.

**Comment by jasonwynn10** [comment]
set debug mode to 2 in your pocketmine.yml file, then post the output here

**Comment by jackjoe84288** [comment]
![received_467244447089739](https://user-images.githubusercontent.com/23036635/44407604-28506b00-a591-11e8-87d6-463201333d17.jpeg)

**Comment by jasonwynn10** [comment]
It appears that you're using a custom installation from the github source instead of poggit. Also, what version of MyPlot did you have before 1.3.6?

**Comment by jackjoe84288** [comment]
I only updated server to 1.5 and update MyPlot, I neither use custum installation nor change any value

**Comment by Aericio** [comment]
make a backup of your `plots.db` file and use https://sqlitebrowser.org/ (or any sqlite browser of your choice) to create a new field inside the table `plots` with the name `denied`, type `text`.

it should look like:
```
CREATE TABLE `plots` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`level`	TEXT,
	`X`	INTEGER,
	`Z`	INTEGER,
	`name`	TEXT,
	`owner`	TEXT,
	`helpers`	TEXT,
	`denied`	TEXT,
	`biome`	TEXT,
	`pvp`	INTEGER
);
```

replace old `plots.db` with this one (make sure you keep a backup before edits in case anything goes wrong)

**Comment by Aericio** [comment]
well in steps:

- open `plots.db`
-  under `Tables (2)`, select `plots`
- press on `modify table`
- paste in the above sql code in the editor, or go to `add field` and add field name `denied` with type `text`.

**Comment by Aericio** [comment]
Issue closed due to inactivity. I am assuming that it now works.
