### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IkeBinGouterSouper** [jasonwynn10/MyPlot#199]
Need Help your MyPlot not working.

Error: "Class 'spoondetector\SpoonDetector' not found"

I use PocketMine-MP 3.3.0 for Minecraft v1.7.0

Please Help me!

**Comment by Aericio** [comment]
https://github.com/jasonwynn10/MyPlot/wiki/FAQ#q-i-keep-getting-this-error-causing-the-plugin-to-disable-how-can-i-fix-this
