### ISSUE TITLE
SQLite3: duplicate column name

### ISSUE THREAD

**Issue by NML32** [jasonwynn10/MyPlot#20]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Getting error in console on startup.

## Reproducing the issue
Start the server.

## Client information
Operating system Linux, PHP version: 7.0.9, Server Genisys-unsupported-b6cec51 (0.16)

## Optional information
Error displayed in console:
```
Warning: SQLite3::exec(): duplicate column name: denied in \src\MyPlot\provider\SQLiteDataProvider.php on line 42
```

**Comment by jasonwynn10** [comment]
it appears that the sql updater is running when it doesn't have to...

**Comment by NML32** [comment]
I also wanted to thank you for all the hard work you're putting in and the quick fixes.  

Great Job!!

**Comment by jasonwynn10** [comment]
:laughing: I'm actually doing this in the middle of my biology class...

**Comment by jasonwynn10** [comment]
fixed in 77ae10b ?

**Comment by inferboy** [comment]
nope, still didnt fix

**Comment by inferboy** [comment]
please fix @jasonwynn10

**Comment by jasonwynn10** [comment]
as a temporary fix, post the db file here. Icn edit it and sendit back for the server to work again.
