### ISSUE TITLE
Have Permissions only on your Plot

### ISSUE THREAD

**Issue by Wertzui123** [jasonwynn10/MyPlot#204]
This woud make thinks like using /holo or destroying (killing) heads from the Plugin "Player head" so much easyer to configure. So with the Admin Command /p permission you can add a permission on the Plot you are standing on and in the config.yml you coud choose what permsissions are by default on every plot, so in the config is 

default-permissions: playerhead.spawn;playerhead.give;...

or something like that and with this config.yml everyone can spawn or kill heads an his plot, but not on the Plots of the others. This woud be very cool!

**Comment by jasonwynn10** [comment]
A feature such as this should have it's own plugin or be apart of an addon plugin. Since I am trying to keep MyPlot as close to PlotMe as possible, this feature will not be implemented.

**Comment by Wertzui123** [comment]
Ok. Do you know a plugin witch can do this?

**Comment by jasonwynn10** [comment]
I don't currently know of one. You can make a request for one on the PMMP forums' plugin request area
