### ISSUE TITLE
API 3.0.0 SUPPORT PLZ

### ISSUE THREAD

**Issue by RainMa22** [jasonwynn10/MyPlot#207]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Yes, I know that Legacy "supports" API 3.0.0. However, it does not work on my PC.

## Reproducing the issue
1. Download MyPlot-"Legacy“ or Tag 1.1.9
2. Put it into the Plugins folder.
3. Run the .cmd
4. And it happened.

## Client information
PocketMine-MP Version: 3.5.7 PocketMine-MP
Plugin Version: Legacy/1.1.9
PHP version: 7.2.1 x64

## Optional information
```
Photo Right Here                                 

```
![default](https://user-images.githubusercontent.com/20056243/51574801-ffe8d780-1e74-11e9-8a98-780f1c726950.PNG)

**Comment by RainMa22** [comment]
Photo Re
![default](https://user-images.githubusercontent.com/20056243/51574760-cf08a280-1e74-11e9-9da5-a6db189a97cb.PNG)
sent

**Comment by jasonwynn10** [comment]
The legacy branch does not support anything newer than API 3.0.0
