### ISSUE TITLE
Custom MyPlot Translations

### ISSUE THREAD

**Issue by FaanMaario** [jasonwynn10/MyPlot#210]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
I can't make my own messages.ini file, it doesn't read the file

## Reproducing the issue
1. make message.ini
2. the plugin don't load it

## Client information
PocketMine-MP Version: 3.6.2 
Plugin Version: 1af8c39a3b77f3b25be795f92e46b4ae9f413fc5
PHP version: 7.2.1 (default)

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by jasonwynn10** [comment]
MyPlot has no feature that allows the creation/use of custom messages. Is this a feature request?

**Comment by FaanMaario** [comment]
Yeah basically :)

**Comment by jasonwynn10** [comment]
If you are able to translate, then would you make a pull request so we can add french to the available languages?

**Comment by jasonwynn10** [comment]
MyPlot 1.4.0 was released with partial french support from old translations. I recommend you use this instead of the `plot-homes` branch you currently are.
https://poggit.pmmp.io/p/MyPlot/1.4.0

**Comment by LeoBdt** [comment]
go on #211 please

**Comment by Aericio** [comment]
French translation has been completed by @LeoBdt.

**Comment by jasonwynn10** [comment]
Completed in cd582325c23810ffcab5be88928a08553833505d
