### ISSUE TITLE
Not working..? 

### ISSUE THREAD

**Issue by RafmexHD** [jasonwynn10/MyPlot#214]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
It doesnt works

## Reproducing the issue
1. Borders Plugin not working, this is the console error

## Client information
PocketMine-MP Version: 3.7.0
Plugin Version: 1.5.0-pre
PHP version: 7.2.1 (default)

## Optional information
```
ErrorException: "Undefined offset: 1" (EXCEPTION) in "plugins/MyPlotBorders/src/jasonwynn10/MyPlotBorders/Main" at line 89

Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by jasonwynn10** [comment]
Borders Plugin is not MyPlot. Please do not spam this repo with issues from other plugins
