### ISSUE TITLE
Perms not working

### ISSUE THREAD

**Issue by LegoFan48737** [jasonwynn10/MyPlot#218]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
Permissions (primarily myplots.claimplots.unlimited or myplots.claimplots.10) dont allow claiming of more than 2 plots

## Reproducing the issue
1. add the `myplots.claimplots.unlimited` permission to a Rank (PurePerms)
2. have that rank attempt to claim more than 2 plots

## Client information
PocketMine-MP Version:  PMMP 3.8.2
Plugin Version: 1.5.4
PHP version: 7.2.1 (default)

## Optional information
Is this something on my end? Or is it an issue with the perms?
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by jasonwynn10** [comment]
The issue is with your permission manager.
