### ISSUE TITLE
Logo Needed!

### ISSUE THREAD

**Issue by jasonwynn10** [jasonwynn10/MyPlot#22]
On the MyPlot website, we need a logo for the plugin that's different from the PlotMe plugin's logo

**Comment by Aericio** [comment]
@GatorThePlayer Please <3

**Comment by jasonwynn10** [comment]
It's the way the site works, the picture is duplicated next to itself 15 times to make the header

**Comment by jasonwynn10** [comment]
I have an idea for what we will do, but I need a new background picture for ours that shows a different plot setup from theirs

**Comment by jasonwynn10** [comment]
nvm, I'll get this done
