### ISSUE TITLE
Messages as config

### ISSUE THREAD

**Issue by Wertzui123** [jasonwynn10/MyPlot#222]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
What problem do you have?
I always have to make a pr when I update myplot, because my custom messages.

## Reproducing the issue
1. Update myplot
2. Done?

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.2.1 (default)

Has nothing to do with OS.

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by jasonwynn10** [comment]
also, duplicate of #210

**Comment by Wertzui123** [comment]
Oh xD
