### ISSUE TITLE
Plot Merche and custom rand

### ISSUE THREAD

**Issue by note3crafter** [jasonwynn10/MyPlot#224]
Can you add custom rand and merch [2 small plots to one big plot]?

**Comment by Wertzui123** [comment]
It's called "merging". And no, it isn't easy you think...
/p border is curently avable by a plugin script.

**Comment by note3crafter** [comment]
I know that it is not easy, but you could start to introduce something because somebody has to start

**Comment by Wertzui123** [comment]
You're right. Please start with plot merging (:

**Comment by note3crafter** [comment]
this plugin is for me to big oof

**Comment by jasonwynn10** [comment]
duplicate of #59
