### ISSUE TITLE
Terrain Glitch

### ISSUE THREAD

**Issue by ChrisNML** [jasonwynn10/MyPlot#23]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
When Generating a new Map the Terrain glitches and generates like a normal terrain map instead of plots

## Reproducing the issue
Generate a new world, Fly in one direction until the terrain is glitchy

## Client information
Operating system Linux, PHP version: 7.0.9, Server Genisys-unsupported-b6cec51 (0.16)

## Optional information
N/A

**Comment by Aericio** [comment]
Glitched chunks / server not sending chunks fast enough. Can't fix that.

**Comment by Aericio** [comment]
^ oops :P

**Comment by TDMidkwhatisxd** [comment]
I dont! It only appear like a normal map if your internet/whole server is slow!
Wen tested on Genisys/Clearsky, i did /p generate and /mw tp plotmap!
It appear first as a normal map (maybe chunks from the map i tped from).
Then the plot was loaded normaly and i could claim and test commands!

Tip: wen a map is first loaded, and u tp on it, it will show some chunks from the map u tped from, well, many chunks , i dont think is from myplot!

**Comment by Aericio** [comment]
@ChrisNML Download ManyWorlds and try, that might work.

**Comment by NML32** [comment]
The server isn't using multiple worlds. The older version of MyPlot doesn't have this problem and we only updated to this version because 0.16 broke the perms.

**Comment by jasonwynn10** [comment]
Have you tried restarting your server? Rejoining? What about just a reload?

**Comment by ChrisNML** [comment]
Yes we have tried all of that aswell as generating new worlds, multiple time

**Comment by jasonwynn10** [comment]
why are you using unsupported genesis?

**Comment by ChrisNML** [comment]
It's only labeled as unsupported because it isn't 100% ready for production servers.

**Comment by jasonwynn10** [comment]
Have you tried running it on other server softwares? The server you are running seems to be the only one that is having this issue at the current time.

**Comment by ChrisNML** [comment]
Yes we tried another software today got same issue

**Comment by ChrisNML** [comment]
We have switched to using v1.0 again FYI

**Comment by Aericio** [comment]
@NML32 Just tell your players to type ./p (cmd) :D

**Comment by jasonwynn10** [comment]
if there are no more reports of this issue, I am going to mark this as wontfix

**Comment by Xelcronia** [comment]
@jasonwynn10 I have the same problem.

**Comment by jasonwynn10** [comment]
I have no fix for this. There is a problem with your server build because the world generator works on all other servers

**Comment by NML32** [comment]
The old version of MyPlot doesn't have this problem.

**Comment by Xelcronia** [comment]
Hmmmm...

**Comment by jasonwynn10** [comment]
I haven't changed the generation from the old version

**Comment by jasonwynn10** [comment]
https://github.com/wiez/MyPlot/compare/master...jasonwynn10:master#diff-7dedd3d1482a10490b4ac4f58f73d4a4

**Comment by NML32** [comment]
All I know is Plots generate perfectly even new worlds.

**Comment by NML32** [comment]
^^Using the older unsupported MyPlots

**Comment by jasonwynn10** [comment]
weird
