### ISSUE TITLE
Denied users can still access plots

### ISSUE THREAD

**Issue by WolffyTheReal** [jasonwynn10/MyPlot#231]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Denied users can still access the plot they are denied from.

## Reproducing the issue
1. Deny a user from a plot.
2. Let the user try to wander on it an watch him achieve this, which should not be possible.

## Client information
PocketMine-MP Version: 3.9.4 
Plugin Version: 1.6.1
PHP version: 7.2.1 (default) I guess but i can't check since i dont have access to the root server console.

## Optional information
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```
no other files that show the issue and no crash dump since nothing crashed.

**Comment by jasonwynn10** [comment]
what data provider

**Comment by WolffyTheReal** [comment]
I'll ask the owner real quick.

**Comment by WolffyTheReal** [comment]
it could be Aternos.org but not sure.

**Comment by WolffyTheReal** [comment]
Ok the owner said its hosted on minehub.de

**Comment by jasonwynn10** [comment]
data provider meaning how the plot data is saved. it's mysql, yaml, json, or sqlite

**Comment by WolffyTheReal** [comment]
whats the default?

**Comment by WolffyTheReal** [comment]
sqlite

**Comment by Akuroma** [comment]
same occurs with mysql data saving

**Comment by jasonwynn10** [comment]
Can I get a video of someone reproducing this? I am unable to

**Comment by Akuroma** [comment]
I just saw, that I'm using version 1.5.4. Maybe I should update first, before commiting an issue.
