### ISSUE TITLE
I don't know how to set up the plot world

### ISSUE THREAD

**Issue by jamesisverycool** [jasonwynn10/MyPlot#236]
How do I set up the plot world tell me please

**Comment by jaylac2000** [comment]
/p generate <world_name>
example: /p generate plots
if u have multi world or anything use /mw tp plots , to get to it

**Comment by provsnoobgaming** [comment]
yep problem solve i guess.You can close your issue now

**Comment by jasonwynn10** [comment]
Does no one read the command arguments???
/p generate world true

**Comment by DenielWorld** [comment]
wHat aRguMenTs? lmao

**Comment by jamesisverycool** [comment]
I'm sorry I didn't see
