### ISSUE TITLE
An error occurs when the generation command is executed

### ISSUE THREAD

**Issue by FUGAMARU** [jasonwynn10/MyPlot#24]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
K2...Level name
When /p generate K2 is executed, an error is output to the console after "Spawn terrain for level" K2 "is being generated in the background" is output.
/p generate If you try to enter World K2 after executing K2, "Building terrain" will be displayed on the client screen and will not proceed.
By the way, a crash dump about this problem was not generated.

## Reproducing the issue
Execute /p generate K2 using 5c009a2

## Client information
ClientVersion:0.16.1
ServerOS:Ubuntu14.04 LTS
ServerEngine:Genisys
PHPVersion:7

## Optional information
[http://writening.net/page?zWJWZA](http://writening.net/page?zWJWZA)
This is the full text of the error

**Comment by jasonwynn10** [comment]
This is not an error. being generated in the background just indicates that it it working. The world will be properly generated after the server is restarted.

**Comment by Aericio** [comment]
@jasonwynn10 Check the "Optional Information" part.

**Comment by FUGAMARU** [comment]
I found that when I edit Config.yml, I get an error.

Config.yml after editing...https://www.evernote.com/shard/s465/sh/24760e0f-755d-4438-bbb4-9050124eef7c/53640baf8317f41a3d668198646d5e4e

Is there a wrong in this Config.yml?

**Comment by jasonwynn10** [comment]
what was changed @FUGAMARU ?

**Comment by FUGAMARU** [comment]
I'm sorry, but even if I run the /p generate K2 command, it will only output "Usage: / p generate <name>" and the world will not be generated so it can not be verified.

I am using the latest commit.

**Comment by jasonwynn10** [comment]
But what was changed in the config?

**Comment by FUGAMARU** [comment]
Changed Line 48, line 75, line 77, line 79, line 82, line 84, line 86.
Please check Config.yml after change ...[Link](https://www.evernote.com/shard/s465/sh/625b5f18-ec53-4a8d-bd7b-84e2638fdd56/020608d2f04b436078a216d341890cfb)

**Comment by Aericio** [comment]
##### Easier to read:
```
[47] # When a player enters a plot, a popup with basic info will be shown
[48] ShowPlotPopup: false
[...]
[74] # The size of a plot
[75]  PlotSize: 35
[76] # The height of a plot
[77]  GroundHeight: 128
[78]  # The width of the road
[79]  RoadWidth: 6
[...]
[81]  # The block that the road is made of (Default is Oak Planks)
[82]  RoadBlock: '45:0'
[83]  # The block that plot walls are made of (Default is Stone Slabs)
[84]  WallBlock: '43:0'
[85]  # The block used as the plot floor (Default is Grass)
[86]  PlotFloorBlock: '1:0'
```

**Comment by FUGAMARU** [comment]
@Aericio Thank you for your support.

**Comment by jasonwynn10** [comment]
is this issue using the latest version?

**Comment by FUGAMARU** [comment]
Yes of course.
