### ISSUE TITLE
how to use myplotborders?

### ISSUE THREAD

**Issue by GuckTubeYT** [jasonwynn10/MyPlot#244]
hello, i want to make plot borders, but how to use it?

**Comment by GuckTubeYT** [comment]
please answer

**Comment by DenielWorld** [comment]
Adding unnecessary comments will not help you to get a reply faster. I believe the README.md should provide any information you need, and you can also find many guides online.

**Comment by jasonwynn10** [comment]
Please use the discord for questions https://discord.gg/QR3QGkj
