### ISSUE TITLE
Fencing

### ISSUE THREAD

**Issue by supercrafti** [jasonwynn10/MyPlot#255]
Where can I find the proportion in the configs where I can set it so that players can no longer reduce property limits

**Comment by Wertzui123** [comment]
Ask such questions in jasons discord or in your already created issue #254 
https://github.com/jasonwynn10/MyPlot/blob/master/resources/config.yml#L81

**Comment by supercrafti** [comment]
This is not in my configs, although I have the latest version

**Comment by Wertzui123** [comment]
Update your config, IDK if MyPlot has a auto config updater

**Comment by supercrafti** [comment]
How can I update the configs?

**Comment by Wertzui123** [comment]
Copy & paste

**Comment by supercrafti** [comment]
Okay, danke
