### ISSUE TITLE
I cannot exhibit the dismantling of property borders!

### ISSUE THREAD

**Issue by supercrafti-lab** [jasonwynn10/MyPlot#261]
I cannot exhibit the removal of property edges, it does not work, but I do not want anyone to be able to remove the edge! Please fix that!

**Comment by jasonwynn10** [comment]
Not a bug. Turn it off in your config

**Comment by supercrafti-lab** [comment]
I switched it off. in the worlds configs and in the normal configs, it still does not work, everyone can reduce their GS edge!

**Comment by jasonwynn10** [comment]
have you already checked that your permissions are correct and `*` is not listed on the helper list?

**Comment by supercrafti-lab** [comment]
I do not mean that. nobody should be able to dismantle the property line!

**Comment by Wertzui123** [comment]
Unset the admin perms with a perm Manager

**Comment by supercrafti** [comment]
what do you mean, I just want to prevent you from changing the boundaries of land!

**Comment by supercrafti** [comment]
What do you mean by that? I just want that you can't change the property boundaries! So that nobody can change them.

**Comment by supercrafti** [comment]
Supercrafti-lab is my second account

**Comment by jasonwynn10** [comment]
then remove the permission for it from the people you dont want doing it

**Comment by supercrafti** [comment]
I just want the plotowner not to be able to mine the boundary of the property!

**Comment by Aericio** [comment]
then remove the permission for it from the people you dont want doing it!
