### ISSUE TITLE
Not in Config!!

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#265]
Where should you set here that you can not remove the edge?
RestrictEntityMovement: true
RestrictPVP: false
UpdatePlotLiquids: true
ClaimPrice: 0
ClearPrice: 0
DisposePrice: 0
ResetPrice: 0

**Comment by Wertzui123** [comment]
EditBorderBlocks

**Comment by MonoAdrian23** [comment]
Doesnt work
