### ISSUE TITLE
Player can't eat

### ISSUE THREAD

**Issue by Crasher508** [jasonwynn10/MyPlot#267]
### Issue description

- When a Player would eat enythink in a Plot, the hunger bar isn't filled(, because PlayerInteractEvent is cancelled.). 

### Steps to reproduce the issue
1. Install MyPlot and start Server
2. Go into a Plot World
3. Try to eat (Hunger bar not filled)

### OS and versions
* PocketMine-MP: 3.11.7
* PHP: 7.3
* MyPlot: 1.6.11
* Data Provider: sqlite

### Other Plugins
- MultiWorld

**Comment by TungstenVn** [comment]
cool,now player will gonna die in their own house cuz of being starve

**Comment by supercrafti** [comment]
I have the same problem!

**Comment by PetyXbronCZ** [comment]
Same problem, pls guys fix it.
