### ISSUE TITLE
Crash from PMMP because Copy

### ISSUE THREAD

**Issue by suerion** [jasonwynn10/MyPlot#274]
PocketMine-MP Crash Dump Fri Apr 3 20:21:16 UTC 2020

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes)
File: plugins/BuilderTools.phar/src/czechpmdevs/buildertools/utils/Math
Line: 37
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BuilderTools v1.2.0-beta2

Code:
[28]  * @package buildertools\utils
[29]  */
[30] class Math {
[31] 
[32]     /**
[33]      * @param Vector3 $vector3
[34]      * @return Vector3 $vector3
[35]      */
[36]     public static function roundVector3(Vector3 $vector3): Vector3 {
[37]         return new Vector3((int)round($vector3->getX()), (int)round($vector3->getY()), (int)round($vector3->getZ()));
[38]     }
[39] 
[40]     /**
[41]      * @param Position $position
[42]      * @return Position $position
[43]      */
[44]     public static function roundPosition(Position $position): Position {
[45]         return Position::fromObject(self::roundVector3($position), $position->getLevel());
[46]     }
[47] 

Backtrace:

PocketMine-MP version: 3.11.6 [Protocol 389]
Git commit: cb9e79b3985719671bd5cbaa7f665b04a6d33359-dirty
uname -a: Linux alpha 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64
PHP Version: 7.3.14
Zend version: 3.3.14
OS : Linux, linux

Loaded plugins:
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
Worlds 3.0.3 by survanetwork for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
StairSeat 1.4.0 by korado531m7 for API(s) 3.9.0
WarpUI 3.3.1 by XenialDan for API(s) 3.11.0
StarterKit 1.0.1 by TheNote for API(s) 3.9.0
MyPlot 1.6.13 by Wiez, Exxarion, jasonwynn10 for API(s) 3.4.0
PersonaToSkin 0.0.1 by XenialDan, DenielWorld for API(s) 3.11.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
VanishV2 1.5 by superbobby for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWgtz20aS/itTdOoiZwmKL5EiU9o6ryRfXLEiriXbuQ23XANgSGKFV2YASUwq//2+7hm8KOWx
OV/VuVIRMY+efn7dPcDPvU2mE1l8ulfaRFnaW477vSJKVG85Ojk9WUxPxvNZv6e0znRv+XOv2OeY
6l1+unz37vpdr99LlDFyS2Ov4jh7UKFIVJLpvTDRT0pkGzEazifz6eh0PBX+vlBGqMedLE2BlUeF
jvCnyITE3kAWSkyHi5ld9xLEN1FMlPO43EapOf5bGcWh0rdZFptBvpP62OjgOPhJBbs8CdW9Ofbt
ioJWHJdFhP9fyWIHUnGUgtRk/kvfkfsUpfdZfK8SlRY4I4y0CopeNYuR9mkYD7JQkQbGp5gTX4n/
zGVwB8lF+8z1mg/F8vGClx3j52SIn0EsjRHEjPiZxkYYo79jWoZ/x199RY8T92gP0DIRH8BWpifi
i3v7g1ZNW6u0KkqdPrvspF7GbMzcY176cRQIU8gCfzZlGhSwvNBZmYaOzNEhuZfL+gRmf16Rxj/H
QaoeqjVHR1FavGSCRxUF769bVXx/9PJlX/za7H//5uw/MPvyazr81B3+Cz0srCKnw44ip6Mnilxl
JmJBv8jdL1o3fqrK5xdOOsqcTv+AMitCR08pQp/1ICl0evJUodWC5XKjs+Ta/xeUcWRUvFkuO7Zq
iPabA1hlb9W9io+s1qazltamZL8eYqHQMoBb//DPfm+rUqVlTD6eSgKA3ioL7lRxhcjxrlbY5Uuj
GqDoTQaj0WBG4xQBAIz5YtTvReYTQrG33MjYKISTzoosyEB2crrAIREFW+Av1HzhTxanJ/PRYjYf
+eFJ4Es538xmJ/5wKmfhZDI5WXiIymKPE7S8iyMfO4eD0XgwxEjpeHwbpeUj8ANwIKaDxWDojUae
TMLZVLwYiZurlbhQfiRTnhydLrzJX0LlL8qxOBoPRwtaPRq9FI+ns0+zKYX/LgfV+QDC0eNPKg1Z
VPeM6U+Zqc7FAD/E/FBDiyEdduCj0ekBqjTaHA0gmOerQo4xLstil2ls/KF3Tvi2uroAvmHiQ/QY
3Z3/oweDyTyi+clgCI3gWaXSjxXYLXQJzYcqB/PGGtdkm+KiPZBIBrkWeK7XXSQ74DTOJGlidX1z
+/H63dsLDD0oH85GUu2KIjfL42OYd1f6gyBLjltsd4Cb1PQx03HY1oobaOuDxJp0NWFKfS9TVTxk
+u5zKYBprtcPzMB6XTPyh8R15h4wkYHj7PiFJUaCrkqtVkonbVmbsa75p4fizqavXw+H4j/ESmcU
+2/STZRGiIfPJPone8B6XXPU+vknLM57Xapu6EALN4WM9I2SRUsLzdihFoZdLdxlWobZyWSUzDuC
L/684C2S63XNSOvn7wnPPix1/v5N24ftQNeHARtdcb5XaSTjC5l2hAGQ/mlpHpliKFN4L7OwXr8F
80r/ESkgsi6U/jY6sE012DXO8FCa2536LgOxz2QYR44t4ThYr69o7g+IcrVfxVlbDDfQFWE2GB2E
2cdI/YSRy8dHqW2u/5c0WfqwT9PRsCPZ9N+VrHcZZGmW7F+tyC9cOs1SRSnt0hhUnrCcWV3i8eLy
Q+SOZwy6KfYxm/BSmv15liQyDV+VRYaSOO41GrMyQkmVrE5NN7ev3t2+Xz1REmISssnb7OaO9jeg
1Blvq2z41OqND4Nv/FYxs/x/4dEdvv4dx1a1em9XLTk7w4fpt5t4PxPKtk9crw/O/10xPsg0MrsP
45YI9VCX/ZPDXJkr7We+v/98mbKiuF5XPDS/fl8YKo+oEFcIbGZxcNwpMLmjI+aM0hBsgMoRBxaR
ogrrxap+EucZEuFWUHO41uv0xWsdiVe5FhMxmiyHo+XJTLy/PRfj4XhI87FMtyUatbNQlfScZEV4
RmcGWm4K79soNOJvKtTghabt6R4p+/dX5ZkuzkaL0WRMg1tJvW+ozkZ8jnz08ljuIe3ZCXNicvmQ
elQRK+4SzkYzGn7YQUVeHJniLEtpwFrH+7FUen+WbTatMQ1AqYZkmqINCJQ7xZPBLlK2oTWOEpp7
zNd8uY3Qcxhkun7O73O3Pow2mygo42J/ZiXingBdhmdUUUTp1pyxSqmvsCoCUodFM2aUCltL6Lrg
7OLy9av3b29plNgf5OiEUSKFZ1/xPwgCXPOMvFeOi/tIPaD0R08F6c5OaejRzx49cm+3hEpxdp4E
Jhrsk5h8RFCqEAG7Rwm2qbkiLxFQg+j4GrxGINkYJSq5hNRKFDslAM8GP2QhAlJwIXwlojSIy1CF
+CGeeCfRuskSvuwontI0cqP6IsOMNkRS+FrJO7HPSu1oiWgjYJ5oE/EJsAxdRcR7IvwdmuqK3HGo
NhK2MeIhS78shMxzJbUg7SXUfco43hOHxS4yVu6HnUpFmW9R7oDAYJ2S41piy3UqxIuPO0WM0RUM
cCmkexi0spqZR2uYmlgW9obGsUrXNCAMfcaqYH2hdYgCJXbITzFrMCHK1vGq0FsK7gZpwuzKIswQ
Bu7iaCnWvRtL+6HUoRLfKF2mgIgthN1pla57zCnfLgkKEjAnXOEt7iMp/k5hQms4Xjw3tRQEbbz1
ZoedkvzCZGDRHWyVIx0pURqYHTgI1bPISNlYCThFVwAizYx3TyhoVOuAS47NihIUISi6BFwEViB2
/b1wtqP1LpTr6ZZ2XnxEeocLwpAyDIVWxtqbWIWF78CSRLPBMS5gZV+RVmAN9WMpY7LTNrrH2nsZ
l0ocuUMBhS+Juj0RIKIItzzYebtVeolpPvu7MvFhBrjxK7NPg1tp7gQ1NHDcAS94b6AYiqVKUlq2
0yhxSrgLlpu+4N5HONxAAPahiwS6M5SoWDfICTSWlClclpZY4jfsT5AJbq2zxwguraAGiMShktbM
kW4dQ282FBx8gYgg6Iuo+BLqKzRvCxXBLPvowWZxBBlgcDFmtbAYnpN0yaQOg0Oy98ExUzJnSNiW
5WwE7pnNQKDPdb9FEm13QA8tza7fjnbnmaQRrcu8sKNWYaSYBLw5udi4cDioCWHp7kjvsygE289z
QD5CPpdB0fCuQcvRsNizi2pPQ3biW1qLAv8VZz68hxJ/dXsbR0lUEJgkaiv5PnYgbqyqh6zcyBBt
3n5LVnuIWPPsUUCJB88SqpzMsISbCCwCAsF9yrQ2WqnqSOvksFbJ4bnNYKiMcIG8gg7aMpses7YU
Q5ICpzPmF0AKGf6/l4Aqqd/inxLz/45/U2Q5s+DwumbJkTMC8EEJWIU1Q3RqxdVoOJ46xhgEPnJU
OP7Ml5+BQ44LZokQQwQlsl2KbCfUowpKRvfMsmwjkrJjvVo9BigwTCORBa7r28uluP3mzY14++bq
zS3Ae/X2zeWNWF2+EyhFv7181xdYJG6vsepSfPzm+u2lWL27Pr+8uRkcQkBHH+OTmVMHOpEo4wqA
gNiQgMFOMSSzNmqwHUH3yDUhYwsv8QCFysIsk0IBCzkB0PAmkvfXnM06GcpDyrgpLXOHMWVLBNDb
ALnNSHzGNeUQKix4w+DpavIF1wbAbLkKqP6wmiV2rV3t3loGuJfKTSPqZOhkNS+fZ8lJPnGSb6X2
ERlekMWxLYEZgJ7XLocaseN2CbcL2I1muORqp80JKsGS3hv1q5xw6ISVG9r0utmAlpU3aUJwIK4t
5luHR7mSlXFY8xIhiTykouHfWMI5sw9BZ8OhkxWnvWaweJIk2XUshVo2uuGvkq3d7VZ4bddsW5ik
cZZ84hviGZfqeMdNVaGSyTROIjd0jhyWSW7LOVszCjfh0URlrwta5DYw78xmJQGekOYR7PIZBSNp
I/HhhHs4mTGlImAodrDatipvCbTotIarfmVIWyO4KnZguaGlv6onasOCXZnemYr3c5nTaJSUCXIs
0qsWVbNBhhS2nbJcNHqleHGq5Ih56mOo7nPHER/oUdldIulOa4tdZHbq0KepNiLUs/Tt4iqELC23
sC0ZVw5egLZP1bJdgBWuVVA+kvbAnS0wLBV6Z6mos6E9VsJGOmxz+rTyVCfT4qbaJQXG1Hc4ur9N
6rf8cJ26G/OlSxEozXZZbEtMXxZoZ6nUZ5ZRNcGFXJJhbLOtlpu1qcVXdbFp09uLtpWqKYJVvS+I
eF94o5YB2Xh8sFdUzLgUwKjd1LHc3VIJGVrJqXniQp82Y9CxNRDfoBaEL51xcSfOV+/72AsefMTX
QxTC7blWsOhZ0/eY/lLMq7K7qcgNa6e1diBehQCqnYw3x+hdbZsQKviwOwqHCrqaIQdrBWKT9lrE
2q3I5SOhGpWYMu5b0KSjP0Yp+jeIBvRRjGVUSb9fpauqDm+aUWozaNMDMirRLPM099zzQeNz5QKS
PxuoTE0Ve2VhujerqilU9NZzWll3uhi7DwcGYuX2xFJveYN0XbFzEz5xo+WWpIO5IJbJYy5mqNVN
wDzhgNRkwvM4ohsV7t01+ixlCnF1+545NRCJxPbLQtBdAVu5Oc72HYMKhpKi9GjXkrmlAAiVX26X
VS/zVzGiHsZVctS18nzVsRrb3Kuqk6VtzlFGRMzilqV2vsvQo5JzVi2MqppUBrdQFlIYeV+BKN2+
VPdINNfEu0ROBxIoWVQYA07ty92qZOZ2Cy7E5YrJUaFx+ZJmQRzlgvdCj1dyDx2SsyTZfdXBEvw7
zGTc8qo5e6Rp0KK6X2pfX9zy/YN1APsdi7254bXO2qVxrX4Ary8sLrg9nt2Dli+9j2I6xCKei2Z3
BkG2TLd1SZ3Spvgwc/SrVZ3Lq2cvjGyP9yrJSvLojYVm5+CkSHtnyKmIgpk7d5iFfnMuweZ3nFla
m1nsVNlO0VeWmK825I987cjJYFfZn03Ot5GdHGXFp4Nq8RGXQh6yClkCBlmhAP/PcTl8nk3JHy7w
rQu7IZitNtPfmpsJ+zb10V6Zwx+VaWFFQOmHD+JL09ZFzJsLPsyPM6ohKSBJn0qTnVHVArgS4aQT
7t6hynW8pyM66HliLF6ILToW06inuduoNTR4qiIXqg8y4pYGsIF639omz/IyrlzRPRDo8xoHEKd0
HpfCXu5imqCVwnQpqiKT703tZc7SpTu6e+IGyw7bbOHMBT6aW4GwURu5u0efNx0M1bHWHc53qMs2
WcsgCDHPvg+uV+4yMgyzMsiTJB9EGXOcZuk+oQaBP5gxkNA0rFPX4+ZFM88iMF7J7Vaj1bTXSvW9
HZVR9BnL3aF8zB8C+Priegl9eA4BbSIgRHhQtgqV/O0SnWiY8UYAHhu0bpqRd2rNW8+0xnmiVNjT
zjtfQspLPQfc7WKKx7O26lCfpuQmrTuevv3ApS/o8xDOVkVdrwB3Nwo9NEwIAEopG9jZKqvYGyPZ
uTNyL45a2aZEbYbExiBWYYUjyJa389UZTyxtZW2bukADXQO1S0dElNZXVQNZlvCSDuTLMLepuvgc
NAe4mfYJlTZ/O+E51LbWtVHRumOoLoWLqHD6rG4Tdm6QAYPaAVdhOsCgy1kU8SGXWNGmJoQ6HYLY
q38CoKrFthAHeg4hq7Qm40gaV7+j5JJJHldPVAGAR2erZWU0Owe/pbuepfiBUzeSZ58vf/5JRO0H
KHWObL+SYDGojNJR6Nrr6h0P983PJSzO5pyeDVeS3JbBPhF4dbm2zb49l3mwPwW9FaKkYJNXc+JS
vH776nY5/nreP1k8jvqTx0l//PXo61AFmYXYo0IrPABbz06HFont0/Tkpa157G1/u6u1EU6pBTp2
l05cd/CtEawW7OklRxkUpa4wuSrldX2Nz4gDOshUAb+XMZXCvOodA3zBFncvXjPU8FG8vkOk5ELB
fXXaGvG40ho092NZzo2gegTwGdcFBXdULBuu+KERP0KZurcNM68jecEKanSbRWzMWCmZPn1DV2N1
r99Tj4VKyY/4m6RzFAjt790oitvPceQ/8su1egROkRrTGcqDLhHzI5hUk853dPbzvfrZDxL6Lrc1
Qu+V0lDqzpje50XGHyHYD2kC9/1xs6LUHVaQ4fE4Hg4no9F4Qd9yGPd+fM4fFt2s3naWG/fqf2G/
Ngact6c3RedjwG3YeUo6kzukuo4SUABCnM4WjpXQfsc4ZoES375ua69K9lAgf3bofokT+gZjTBf5
AiXJcHQynA7n+PnFG4TVPAjw32KmZvOTzSycj9VJsBluxrP5ZnqqRrN5MJa+P56ILyraUdd4adFR
4eriujMfZp941+GgtXJn565rviZvfuKqyH4bzR9xsjHoW9XHzgZ37cafTkFB9CFpv6cVrEweuy2t
Pqv979TGXZ50FL9Lso5lbiJCpe+vOpY3zJtpD0VbP0ql3ttPW/lrkCK7UykKso5YBwGBR2L6yZoH
HR24017yzjGsyTER5ex9oxM8/vLL/wBqCAoX
===END CRASH DUMP===

**Comment by jasonwynn10** [comment]
Please read

```
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BuilderTools v1.2.0-beta2
```

**Comment by suerion** [comment]
uuaarrggg sorry, you can delet this, false github
