### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by MorpheusTP** [jasonwynn10/MyPlot#28]
Hey, I just saw that a German language Pack already exist but may I also help with translating Stuff in German (Deutsch) ?

**Comment by Aericio** [comment]
Sure. If there are any needed language files, just create a pull request :)

**Comment by jasonwynn10** [comment]
Actually, the german language pack needs updated. I am going to go through the languages and add all the new commands soon. Those will need translated

**Comment by MorpheusTP** [comment]
Yop. Just tell me when you are done and I start translate it (:

**Comment by Aericio** [comment]
Can we close this for now? Its not actually an issue. Just create the PR when we update the english language file.
