### ISSUE TITLE
server crashes with redstone

### ISSUE THREAD

**Issue by adsfasdf324** [jasonwynn10/MyPlot#280]
the server crashes whenever i use this redstone plugin,

it happens whenever someone clears a plot, everytime a player loads the cleared plot, it crashes the server

https://github.com/tedo0627/RedstoneCircuit_PMMP-Plugin

myplot 1.16.13
redstonecircuit 2.0.0
pocketmine 3.12.0
php 7.3
[Mon_Apr_20-05.45.38-WEST_2020.log](https://github.com/jasonwynn10/MyPlot/files/4501211/Mon_Apr_20-05.45.38-WEST_2020.log)

**Comment by jasonwynn10** [comment]
If it only crashes when you use the redstone plugin, how is that my problem? Go complain to teh developer of that plugin instead
