### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by GamingonTour1** [jasonwynn10/MyPlot#286]
Class MyPlot\subcommand\ClaimSubCommand contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MyPlot\subcommand\SubCommand::getForm) in phar:///home/cb1/plugins/MyPlot.phar/src/MyPlot/subcommand/ClaimSubCommand.php on line 69

**Comment by jasonwynn10** [comment]
Use the releases and release branch. Dont post errors for WIP branches 🤦‍♂️
