### ISSUE TITLE
Block placing (water, lava, bucket) and Player denying: Ender Pearl Bug

### ISSUE THREAD

**Issue by suerion** [jasonwynn10/MyPlot#299]
### Issue description

- Expected result: 
1. Blockplacing on an plot from an other player without an plothelper should not work  (will try the latest version, if water and so placing would not only on road fixed, i will look on plots also)
2. After Player denying, the player should not on the plot

- Actual result: 
1. We could on an other plot from an player place water, lava, buckets and some other blocks
2. After a Player was denyed on an Plot, he could teleport on the Plot with an ender pearl

### Steps to reproduce the issue
1. Placing lava, water, buckets on the plot without Permission does work.

2. Player could teleporting into plot, with ender peals, 

### OS and versions

* PocketMine-MP: 1.12.5
* MyPlot: 1.6.13

### Crashdump, backtrace or other files
No Crashing

**Comment by suerion** [comment]
After update to 1.6.14, the same issues here

**Comment by jasonwynn10** [comment]
Test this build for me
https://poggit.pmmp.io/r/91225/MyPlot.phar

**Comment by suerion** [comment]
i would test it tomorow, i came back with an answere

**Comment by suerion** [comment]
@jasonwynn10  the block placing on other plots is already enabled, they could build all some blocks on other plots... they had have destroyed all plots already


lava, water, pictures, beacons (pm-beacons), buckets,

**Comment by suerion** [comment]
![problem](https://user-images.githubusercontent.com/55131959/84535611-6a114f00-acec-11ea-9f65-40126714d9c6.PNG)

**Comment by jasonwynn10** [comment]
> we could place water and so things on unclaimed plots and also on claimed without addhelper

This is not a MyPlot Bug.
