### ISSUE TITLE
The Merge Road/\ Players cant Build on the Merged Road on the MergePlot Can you Fix them? 

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#300]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: the Merg function is good but the player cant build or use the road on the merge Plot and pls add /unmerge 😏

### Schritte zum Reproduzieren des Problems
1. ...
2. ...

### OS and versions

* PocketMine-MP: lastest
* PHP: lastest
* MyPlot: lastest dev version
* Data Provider:

### Other Plugins

- If you remove all other plugins, does the issue still occur?
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the PM discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

 not crashdumps
```
Put a console error here, but please make sure you have your debug level set to 2 in your pocketmine.yml
```

**Comment by HimmelKreis4865** [comment]
Hello DragonfireHD, 

as I know, MyPlot-Merging isnt released yet, so there's just a dev build which is **not** supported!

jasonwynn10 is working hard on it, but until you can't find merging as official release under https://poggit.pmmp.io/p/MyPlot/  its not recommended to use plot - merging.

**Comment by DragonfireHD** [comment]
Ok danke Himmelkreis 😉
