### ISSUE TITLE
Question for Merge

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#305]
Everytime i type /p merge north/south or whatever, i get an Error.
Whoops, an error eccoured.
Whats wrong?
Myplot Latest Dev
Pocketmine 3.12.6
Thank you

**Comment by DerDevHD** [comment]
Hello @MonoAdrian23 

**The /p merge isnt finished yet, so there are some errors and debug messages. Please don't open another issue of this type, when MyPlot merge isnt finished.**

~ DerDevHD. 

PS: If you wan't to get merge as fast as possible, contribute to it ;).
