### ISSUE TITLE
Feature request 😃

### ISSUE THREAD

**Issue by EndermanLetsPlay** [jasonwynn10/MyPlot#308]
Hi! Since it is a function suggestion, the prefabricated template is unfortunately not suitable.

My suggestion would be a feature that allows you to replace a certain name from the MyPlot database with a command.

If someone changes his name, it is cumbersome to transfer all plots and data.

So it would be much easier to do this with a command.
For example if someone changes his name from "CreeperHD235" to "CreeperHD", you should be able to transfer all data from one user / account to the new account with the command "/p replaceuser CreeperHD235 CreeperHD".

I hope that this feature will be introduced asap.
By the way, great plugin, everything works almost without bugs so far :)

Best regards

**Comment by jasonwynn10** [comment]
I've taken a second look at this feature request and have come to the conclusion that data modification via any tool which supports the usable data providers is not as cumbersome as it is made out to be.

SQLite and MySQL only needs 1 query for it. JSON and YAML only needs find/replace-all to run once also.
