### ISSUE TITLE
Cake Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#309]
Players can eat cake from the plot edge without being consumed. This happens when EditBorderBlocks is active.
Myplot 1.7.0
Pocketmine 3.12.6

Reproduce: Place a Cake when EditBorderBlocks is active.
Eat a little bit.
Have fun.
Thank you very much

**Comment by jasonwynn10** [comment]
Helpers and Owners have rights to change the border blocks. That includes eating cake.
