### ISSUE TITLE
Where to assign max plot claim?

### ISSUE THREAD

**Issue by rjworks** [jasonwynn10/MyPlot#311]
Where to assign max plot claim? I want people to only get one claim.

**Comment by rjworks** [comment]
I set myplot.claimplots.1 perms to player but they can still get 2 plots.

**Comment by Aericio** [comment]
Add `-myplot.claimplots.2`

**Comment by rjworks** [comment]
ok. so i put that and then add claim to 1?

**Comment by rjworks** [comment]
added that and still can claim 2 plots

**Comment by rjworks** [comment]
i can give players 3 plots claim but not 1..

**Comment by rjworks** [comment]
Changed the default max plots in plugin.yml to 1
