### ISSUE TITLE
/p clear crash

### ISSUE THREAD

**Issue by rjworks** [jasonwynn10/MyPlot#323]
Link to crashdump: 
https://pastebin.ubuntu.com/p/wDZM5WWQk5/

### Additional comments (optional)
do /p clear more times

**Comment by MonoAdrian23** [comment]
Use the latest Myplot Version!

**Comment by rjworks** [comment]
which one
mine is not that outdated
I'm using 1.7.0 which is the 'latest'

**Comment by MonoAdrian23** [comment]
1 7.1 is the latest version.
Check it on Poggit

**Comment by rjworks** [comment]
ok they need to update plugin.yml
