### ISSUE TITLE
Idea for MyPlot dont blame me i just bring new ideas 🙈

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#324]
## Description
I think we need a the /p h to across worlds asample
You go to the Farmworld and write /p h and you go to the Citybuild world on you plot

## Justification
Its a Good idea because other players can immediately switch after farming Getting to their plots 

Idea 2:
Per PlotWorld Money Economy

**Comment by jasonwynn10** [comment]
1. These have been implemented forever. Look at the command arguments or get an autofill plugin.

2. Edit your world config
