### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by mote166** [jasonwynn10/MyPlot#325]
Link to crashdump: 
https://pastebin.com/Evkidm1n

### Additional comments (optional)
**EDIT:** confirmed reproduce way.

run the command /p clear confim on a plot more than one time while it is already clearing that plot.

**Comment by jasonwynn10** [comment]
Not enough information

**Comment by MonoAdrian23** [comment]
Use the latest version of Myplot, its fixed!!!
