### ISSUE TITLE
How can I split the claimed plots of different worlds 

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#328]
How can I split the claimed plots of different worlds because I have 2 citybuilds nevertheless the number of claimed plots is added together by CB1 
And CB2 but the players should be able to claim exactly as many claims on both CBs if they can claim 4 plots 

At the moment it is such an example 

Player has the right to claim 4 plots he claims 4 plots on CB1 but he now wants to claim 4 plots on CB2 as well but now that problem he can no longer claim plots

Have a Nice Day and Good luck for you Code 🙂👍🏼

The Discord link doesn't work 
Discord: https://discord.gg/qqcpp9q

**Comment by jasonwynn10** [comment]
you need a custom plugin to do the splitting logic for you

**Comment by DragonfireHD** [comment]
And what is the name of such a plugin?

**Comment by jasonwynn10** [comment]
Such plugin does not exist. Emphasis on *custom*. good luck 👍
