### ISSUE TITLE
(Feature request) Implement the players namespace at /p

### ISSUE THREAD

**Issue by UnEnanoMas** [jasonwynn10/MyPlot#329]
Hello good afternoon, yesterday a player from my server gave permission to a player to edit in his plot, with the command / p addhelper "Name whit space" and it worked correctly.

The fact is that later he wanted to remove the player from editing his plot and used the / py command then he clicked on remove helper, but when he tried to remove it, having a name in the "Name whit space" space he said that it was not possible since there was no one with the name "Name" who had permissions on his plot

So I don't know if it is possible to add that, to make it more comfortable.

PS: In version # 615 the / p has been removed, will it come back?

**Comment by MonoAdrian23** [comment]
Use /p addhelper "name"
Use everytime " by Players with namespace

**Comment by UnEnanoMas** [comment]
I know you have to use the "but I was wondering if that was possible: /

**Comment by provsalt** [comment]
use 👏 the 👏 issue 👏 template

**Comment by UnEnanoMas** [comment]
It seems ridiculous to have to use when it is clearly explained and it is obvious what I asking for and ask, but hey, do what you want, it only provided an idea

**Comment by jasonwynn10** [comment]
without the requested information filled out, how a I to know if your version is even updated? it exists fro a reason. use it.
