### ISSUE TITLE
Generating a plot world, no terrain 

### ISSUE THREAD

**Issue by ChrisNML** [jasonwynn10/MyPlot#33]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Reproducing the issue
1. generate plot world
2. join server
3. There will be no terrain and you will fall into the void

## Client information
PocketMine-MP Version: PocketMine-MP 1.6.2dev-#60 「Unleashed」 implementing API version 3.0.0-ALPHA1 for Minecraft: PE v1.0.0.16 (protocol version 100)
Plugin Version: the latest on GitHub
PHP version: 7.0.13 (default)

**Comment by Aericio** [comment]
Does this happen on 0.16.2 also?

**Comment by ChrisNML** [comment]
We have not tested on 0.16

**Comment by jasonwynn10** [comment]
This plugin is not currently available for the 1.0.0 pocketmine-MP beta. We will be updating very soon once dktapps completes how levels are being saved

**Comment by ChrisNML** [comment]
sorry we thought it was ready to use with v1.0.0 since they set the api: [1.13.1, 2.0.0, 3.0.0-ALPHA1]

**Comment by ChrisNML** [comment]
sorry we thought it was ready to use with v1.0.0 since you set the api: [1.13.1, 2.0.0, 3.0.0-ALPHA1]

**Comment by Dblcut3** [comment]
I'm glad others are experiencing this! I've had such a tough time with 1.0 so far lol. I'm glad I found this fork and that someone will be updating plots eventually. Thanks for all the hard work :)

**Comment by jasonwynn10** [comment]
Has the API3 branch been tested yet?

**Comment by Aericio** [comment]
Not yet.. do you want me to test it?

**Comment by jasonwynn10** [comment]
@Aericio please do

**Comment by jasonwynn10** [comment]
probable fix for generation 2b3069c
