### ISSUE TITLE
Something that has been forgotten

### ISSUE THREAD

**Issue by UnEnanoMas** [jasonwynn10/MyPlot#335]
Sorry, I have not found the Featured Request anywhere, I must be blind

You forgot to add the /p dispose and the /p reset to the /p list

**Comment by UnEnanoMas** [comment]
I have also encountered the problem that players cannot use the rockets to propel themselves with the elytras, can something be done?

**Comment by jasonwynn10** [comment]
Not forgotten. Intentionally not added.
