### ISSUE TITLE
The plugin doesn't load

### ISSUE THREAD

**Issue by minijaham** [jasonwynn10/MyPlot#338]
### Issue description

- Expected result: The plugin should load
- Actual result: Does not load

### Steps to reproduce the issue
1. Use DevTools to load the folder plugin
2. Generate .phar file using /makeplugin
3. Install the .phar file and restart

### OS and versions

* Plugin Version: 1.7.0
* PocketMine-MP: 3.15.1 or something latest bruh
* PHP: 7.3

### Other Plugins

Yes the issue still occur 
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue? Nope

### Console error, backtrace or other files

23.09 15:58:06 [Server] Server thread/INFO Registered folder plugin loader
23.09 15:58:06 [Server] Server thread/INFO Enabling MyPlot v1.7.0
23.09 15:58:06 [Server] Server thread/INFO Disabling MyPlot v1.7.0
23.09 15:58:06 [Server] Server thread/INFO Enabling MyPlot v1.7.0
23.09 15:58:06 [Server] Server thread/INFO Disabling MyPlot v1.7.0

**Comment by minijaham** [comment]
The enable and disable repeats .-.

**Comment by jasonwynn10** [comment]
LOL thats not a fault of the plugin and absolutely gonna be my problem. Good luck.
