### ISSUE TITLE
Plotworld go's Underwater Please fix this Bug 🚢🏊‍♂️🏊‍♀️

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#339]
So befor you delete the message please look this and please fix this problem but the plot rand border higher please and please wee need liquid water and lava border for roads
![Screenshot_20200929_181556_com mojang minecraftpe](https://user-images.githubusercontent.com/50929188/94585769-c048d480-0280-11eb-834d-9e1545f3cb45.jpg)

**Comment by provsalt** [comment]
How hard is it just to fill up the issue template

**Comment by DragonfireHD** [comment]
### Issue description

- Erwartetes Ergebnis: Das Plots eine Wand haben wo zmb Wasser oder lava auch ohne rand nicht drüber fließen kann
- Tatsächliches Ergebnis: Es wurde am Rand eines Plots Wasser gesetzt und dies fließt nun auf der Straße!!! 

### Schritte zum Reproduzieren des Problems
1tens Platziere wasser ohne ein rand innerhalb des Plotendes wasser odee lava
2. Plot Owner können auf Plot ränder selbst mit slaps oder blöcke trotzdem Wasser Platzieren

### OS and versions

* Plugin Version: build version MyPlot_dev-615 1.7.0
* PocketMine-MP:  3.15.1
* PHP: 7.3.21
*Game version: PE and Windows 

So befor you delete the message please look this and please fix this problem but the plot rand border higher please and please wee need liquid water and lava border for roads

![Uploading Screenshot_20200929_181556_com.mojang.minecraftpe.jpg…]()

**Comment by DragonfireHD** [comment]
![Screenshot_20200929_181556_com mojang minecraftpe](https://user-images.githubusercontent.com/50929188/94654599-8ff34b80-02fd-11eb-81de-44dc50d5833a.jpg)

**Comment by jasonwynn10** [comment]
Unable to reproduce. Check your world config.
![image](https://user-images.githubusercontent.com/16521025/95148021-6056a000-0750-11eb-90d9-afea2748cfab.png)
