### ISSUE TITLE
Error on Events

### ISSUE THREAD

**Issue by starterdragon** [jasonwynn10/MyPlot#34]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Issue on old plots generated using old MyPlots version, I've generated this plots since 0.16.0.. now when I used the MyPlotsAPI3 branch there is a bug on events like onMove and Break etc..

## Reproducing the issue
1. ... generate plots using old version [the I forgot which, but the first build with something like ~.~.13]
2. ... use the MyPlotsAPI3 version

## Client information
PocketMine-MP Version: 1.6.2-dev.#60
Plugin Version: MyPlotsAPI3 1.1.2
PHP version: 7.0.13 (default)

## Optional information

![image](https://cloud.githubusercontent.com/assets/16812043/21514768/d980b5be-cd03-11e6-8d42-c40e46ef180c.png)

**Comment by Aericio** [comment]
Again:
> This plugin is not currently available for the 1.0.0 pocketmine-MP beta. We will be updating very soon once dktapps completes how levels are being saved

**Comment by jasonwynn10** [comment]
the new api is currently in development, so any developmental plugin builds will also be highly unstable and this plugin especially will be because of new  level implementations

**Comment by jasonwynn10** [comment]
what were the specifications for this world within the config?

**Comment by jasonwynn10** [comment]
oops, I need to test the plugins 1.0.0 branch for this issue
