### ISSUE TITLE
Plot Bottom Bug

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#340]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
I have edit Border Block Set to true, and i have a Void Bug 

### Steps to reproduce the issue
1. ... Generate a Plotworld
2. ... See my Picture

### OS and versions
 Dev 633
* Plugin Version:
* PocketMine-MP: 3.15.1
* PHP: 7.3
* Game version: PE (delete as appropriate)

### Other Plugins
 Multiworld, Worldprotect, EnchantUI, FormApi, Economy Api, ScoreHud, PurePerms, PureChat, MyplotHomes, AddNetherite HeroTeam

- If you remove all other plugins, does the issue still occur? Yes (delete as appropriate)
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

### Console error, backtrace or other files

[![Screenshot_20200930_205328_com.mojang.minecraftpe.jpg](https://user-images.githubusercontent.com/59027482/94728344-5ef83280-0360-11eb-8d4f-2485a456e7c2.jpg)

**Comment by MonoAdrian23** [comment]
Many Plots have this Problem but not all.

**Comment by jasonwynn10** [comment]
unable to reproduce with given steps and plugins
