### ISSUE TITLE
MyplotHomes Doesnt Work after MyPlot Update

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#346]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ... I have Update Myplot to Dev 651
2. ... MyplotHomes doesnt work
3. ... When i downgrade Myplot, it works
4. ... I can only use /p h 1 Not /p h name number

### OS and versions
 Dev 651 Myplot
* Plugin Version: 1.9.0
* PocketMine-MP: 3.15.2
* PHP: 7.3
* Game version: PE

### Other Plugins
  Plugins (81): AddNetherite-HiroTeam v2.0.0, AlwaysSpawn v2.3, AntiAFK v0.0.1, AntiNukeBreak v1.0.3, AutoClearLagg v3.1.0, AutoMineReset v0.3.4, Banking_vonfram v1, BedrockClans v3.2, BetterVoting v2.0.2, BlockCMD v1.0.0-beta, BlockProtect v1.0.0, Boats v0.0.1, CB-Heads v2.4, ChestShopXSOAP v6.6.6, CommandWatcher v0.0.2, CoreSystem v1.3.0, CustomAlerts v2.1, DevTools v1.14.1, EXPShop v1.0.5, EconomyAPI v5.7.2, EconomyShop v2.0.11, Elevator v1.0, Emotes v1.0.0, EnchantUI v0.6, ExpBank v0.0.1, FlyBooster v0.0.1, FormAPI v1.3.0, HealthTag v2.0.2, ITEMID v1.0.0[S255][S255], InfoUI v0.1, InvSee v1.0.0, JukeBox v1.0.1, KeepInventory v1.0, KillRewards v1.2.0, LightningDeath v1.2.2, LoadAllWorlds v1.1.1, MCPEToDiscord v1.4.1, MSpawns v2.2, MagicWE2 v7.0.0, MineReset v3.2.0, Monoquest v1.1.0, Monosell v1.3.0, MultiWorld v1.6.0-beta1, MyPlot v1.9.0, NickUI v1.0.0, NoFallDamage v1.0, NoTell v1.1.3, Offhand v1.1.0, OnlineTime v1.3, OreEarn v1.8.1, PeacefulSpawn v1.2, PersonaToSkin v0.0.1, PlayerInfo v2.1.4, PlayerSkinStealer v1.0.0, PortalsPE v1.1.1, ProfileUI v4.2.1, PureChat v1.4.11, PureEntitiesX v0.6.9, PurePerms v1.4.3, RandomWords v3.0.0, RedstoneCircuit v2.0.0, Rewards v4.0, ScoreHud v5.2.0, SignRanks v0.0.1, SimpleBanner v0.1.0, SimpleMSG v1.0.0, Slapper v1.6.0, SlapperRotation v1.2.1, Sponges v1.1.0, StarterKit v1.0.1, TeaSpoon v1.2.0, Texter v3.4.10, UltraCapes v2.0.0, UltraFriendSystem v2.8.0, VanishV2 v1.13, WhatCrates v2.0.0, WorldProtect v2.3.8, XPPerks v2.0.0, Xraycrasher v1.0.0, Zeitbann v2.3, essentialsTP v1.2.2

- If you remove all other plugins, does the issue still occur? Yes 
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

### Console error, backtrace or other files
 
![Screenshot_20201007-114321_Chrome.jpg](https://user-images.githubusercontent.com/59027482/95315184-766c7980-0892-11eb-9451-2362131623e3.jpg)

**Comment by jasonwynn10** [comment]
Not this plugin. Not a problem for this repo.

**Comment by MonoAdrian23** [comment]
![Screenshot_20201007-115935_Chrome.jpg](https://user-images.githubusercontent.com/59027482/95316832-9b61ec00-0894-11eb-83f1-65dc69a178e2.jpg)

Not youre Gist?????

Hmmm i see 😱
