### ISSUE TITLE
/p sell doenst work

### ISSUE THREAD

**Issue by MonoAdrian23** [jasonwynn10/MyPlot#347]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
Players with Permission for sell cant sell her Plots.
Its says youre not the owner from this plot but he owns this plot
Economy is True
Permission is given.
myplot.command.sell
Only OP Players can do this.

### Steps to reproduce the issue
1. ... Claim a Plot without OP
2. ... Type /p sell price 
3. ... Now you can see, youre not the Owner from this plot

### OS and versions
 
* Plugin Version: 1.9.0
* PocketMine-MP: 3.15.2
* PHP: 7.3
* Game version: PE/Win10

### Other Plugins
 Multiworld 1.5.2 
Myplot 1.9.0, EconomyApi 5.7.2

- If you remove all other plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by provsalt** [comment]
![Screenshot_2020-10-08-20-31-45-16.jpg](https://user-images.githubusercontent.com/39023494/95458838-57aad780-09a5-11eb-9dc4-8ad9355e920c.jpg)

Not youre repo?????

Hmmm i see 😱

**Comment by DerDevHD** [comment]
Can you tell us which provider you are using?
