### ISSUE TITLE
Server crashed from MyPlotBorder

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#349]
Link to crashdump: 

https://pastebin.com/cdHj6zmB

### Additional comments (optional)

Crash is from Konsole and in the Plugin MyPlotBorder
Error: Class class@anonymous contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MyPlot\subcommand\SubCommand::getForm)
In line 51

**Comment by jasonwynn10** [comment]
You modified the code, not me. Not my problem.

**Comment by DragonfireHD** [comment]
I have nothing Modified it is your plugin

**Comment by DragonfireHD** [comment]
I cant code mister jasonwynn10

**Comment by DragonfireHD** [comment]
Who can i Modified?
