### ISSUE TITLE
Join projects into 1?

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#35]
I don't have alot time to work on mine. @Aericio and me once tested it on my server. https://github.com/thebigsmileXD/SkyBlockPE
It also is a MyPlot 'fork', generator fully working, and locally is reset works too.

**Comment by Aericio** [comment]
hi bby

**Comment by Aericio** [comment]
dan is gr8 dev

**Comment by jasonwynn10** [comment]
How do you propose that we merge the plugins? Should we just add the option for world type in the generate command?

**Comment by thebigsmileXD** [comment]
What world type?

**Comment by Aericio** [comment]
he made a custom generator.. i guess he means if you want it as a gen in custom generator?

**Comment by jasonwynn10** [comment]
I mean for the player to choose between normal Plots or Skyblock Islands to be used when the world is generated

**Comment by thebigsmileXD** [comment]
Why that. Wasnt it about SkyBlock only?

**Comment by jasonwynn10** [comment]
This repository is just for the continuation of the MyPlot plugins development. There weren't any plans for changing it into a Skyblock plugin

**Comment by thebigsmileXD** [comment]
@Aericio wtf did you tell me

**Comment by Aericio** [comment]
wtf i never told you this was skyblock

**Comment by thebigsmileXD** [comment]
*request lock*

**Comment by Aericio** [comment]
*lock request accepted*
