### ISSUE TITLE
Server crashed for MyPlotBorders /MyPlot_dev-655

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#352]
Link to crashdump: 

https://pastebin.com/9JYe3QpS

I dont modified this i have the Pre Download from poggit for MyPlot Please fix the MyPlotBorders 
😔

### Additional comments (optional)

**Comment by jasonwynn10** [comment]
The plot borders script is no longer being maintained or supported by me. Request an update from someone else.
