### ISSUE TITLE
/p pvp is not working on the right way

### ISSUE THREAD

**Issue by efor89** [jasonwynn10/MyPlot#353]
hi
i love myplot :) but i try to set with /p pvp true that player can turn on pvp on his plots.
but if i dont use worldprotect like /mw gamerule pvp false or /wp pvp false you can do in the complet plotworld pvp.
so my question how can i turn off in the complett plotworld pvp and with /p pvp true turn on only on the plot

* Plugin Version: 1.7.1
* PocketMine-MP: altay newest and pmmp newest
* PHP: 7
* Game version: PE/Win10 

### Other Plugins
worldprotect
multiworld

**Comment by provsalt** [comment]
n o f o r k s u p p o r t

**Comment by efor89** [comment]
-.-

**Comment by efor89** [comment]
its with pmmp the same

**Comment by ImDaRealAni** [comment]
Still no fork support.

**Comment by provsalt** [comment]
No fuck off ![Screenshot_2020-10-14-21-04-26-03.jpg](https://user-images.githubusercontent.com/39023494/95992740-dea5f700-0e60-11eb-90bf-6cf0d7f5e6a3.jpg)

**Comment by efor89** [comment]
i test it with the newest pmmp to and its not working....

**Comment by ImDaRealAni** [comment]
This plugin does not, nor ever will support Altay.

**Comment by ImDaRealAni** [comment]
Check here for details: https://github.com/jasonwynn10/MyPlot/issues/327#issuecomment-681889341

**Comment by efor89** [comment]
yes i now but i try it on pocketmine-mp newest build too and there its not working too
