### ISSUE TITLE
World not loading

### ISSUE THREAD

**Issue by Callum9966** [jasonwynn10/MyPlot#36]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
When I create a new plot world (or use an old one) I then teleport to it and it says I've been teleported, but instead I'm in the same place and all entity's disappear.

## Reproducing the issue
1. ... Make a new plot world (or use an old one)
2. ... teleport to the plot world
 MyPlots_v1, php version: 7.0.14, using: ElyWing-1.0 (codename Birpen)

## Client information
PocketMine-MP Version: 
Plugin Version: MyPlots_v1
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
Please specify the PocketMine-MP Version
