### ISSUE TITLE
An unexpected crash 2

### ISSUE THREAD

**Issue by UnEnanoMas** [jasonwynn10/MyPlot#362]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

**I have not been able to know why or how this happens**

### OS and versions

* Plugin Version: 659
* PocketMine-MP: 3.16.0
* PHP: 7.3
* Game version: PE and Win10 

### Other Plugins
**Plugins are private**

- If you remove all other plugins, does the issue still occur? Yes/No (delete as appropriate) **I can't answer because I don't know how to reproduce it**
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**I don't know**

### Console error, backtrace or other files
I have not had time to copy the error, it has been deleted, but I read something from Claim Price, I don't know if it's something to sell, sorry for the inconvenience, if you want to close this

**Comment by jasonwynn10** [comment]
I can't fix the issue without a stack trace from the console or server.log file. Please post your findings here once you have it.
