### ISSUE TITLE
Water and lava can flow out of the plots

### ISSUE THREAD

**Issue by UnEnanoMas** [jasonwynn10/MyPlot#367]
### Issue description

- Expected result: What were you expecting to happen? **That they could not leave the plot**
- Actual result: What actually happened? **If you put lava or water they can leave and even reach the plots of other players, being able to burn their houses or destroy their crops**

### Steps to reproduce the issue
**In this video I show you how to do it**
https://user-images.githubusercontent.com/63286108/104131414-67f09b00-5376-11eb-8ea6-d6df521b3db7.mp4

### OS and versions

* Plugin Version: dev#662
* PocketMine-MP: 3.17.2
* PHP: 7.3
* Game version: PE and Win10

### Other Plugins

A lot of plugins are private srry

- If you remove all other plugins, does the issue still occur? **I have not tried it**
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

### Console error, backtrace or other files

--My world yml--

---
RestrictEntityMovement: true
RestrictPVP: false
UpdatePlotLiquids: true
EditBorderBlocks: false
ClaimPrice: 15000
ClearPrice: 0
DisposePrice: 100000
ResetPrice: 0
ClonePrice: 1000000
...

**Comment by HighTecDev** [comment]
PR #365 
;-)

**Comment by UnEnanoMas** [comment]
> PR #365
> ;-)

Unknow generator: MyPlot xd

**Comment by HighTecDev** [comment]
Not a Part of my PR

**Comment by UnEnanoMas** [comment]
The difference is that I prefer to wait for jason to fix that because it will work with all plugins
