### ISSUE TITLE
Issues with plot claiming

### ISSUE THREAD

**Issue by Dblcut3** [jasonwynn10/MyPlot#37]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

When I generate a new plot world, it doesnt actually register as a plot world and you cannot claim there.  On old plot worlds, typing /p auto sends you into the ground or void. And typing /p claim gives the Unknown Error message.

## Reproducing the issue
1. Generate a new plot world
2. Type /p auto, nothing works.

## Client information
PocketMine-MP Version: 
Plugin Version: API 3.0 branch
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
The generation issue is known. Please give more information about the claiming issue

**Comment by Dblcut3** [comment]
What kind of info about it will you need? I will be happy to give you what I can to help this get fixed.

**Comment by NML32** [comment]
When I do /p claim I get the following message:
You are not standing inside a plot

When I do /p auto I get the following message:
You are not in a plot world

Not sure if this matters but my worlds folder is empty.
-plugins/MyPlot/Worlds

**Comment by Aericio** [comment]
that shouldn't matter, it should generate a new file if its empty..

**Comment by jasonwynn10** [comment]
@NML32 there are many issue that I am working on fixing, but I cannot at the moment due to my computer being broken. I will attempt to resolve all these issues as soon as I can.

**Comment by TDMidkwhatisxd** [comment]
I fixed generating! Was so simple! Just remove colors, mcpe just need biome id not color!

**Comment by jasonwynn10** [comment]
I plan on changing the way biomes are changed. The colors were the old method, but instead I will set the chunk biome's Id and resend the info to the client.

**Comment by jasonwynn10** [comment]
@TDMidkwhatisxd that has already been done though. There is another issue that has to do with PocketMine's new chunk system

**Comment by TDMidkwhatisxd** [comment]
I dont have problems! At all!

**Comment by Lazerplayz** [comment]
Did you change all FullChunk to Chunk ?

**Comment by jasonwynn10** [comment]
@Lazerplayz  I have on the API3 branch

**Comment by keithkfng** [comment]
@jasonwynn10 for your reference this one actually works quite well - https://github.com/jjplaying/MyPlot

**Comment by jasonwynn10** [comment]
but that only removes color, which was already replaced in this version

**Comment by keithkfng** [comment]
@jasonwynn10 yes, but it isn't forked off your version, it's forked off the original. Which means that your previous changes may have caused a problem...

**Comment by jasonwynn10** [comment]
maybe this will fix generation? 2b3069c
