### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by EndermanLetsPlay** [jasonwynn10/MyPlot#378]
Link to crashdump: https://pastebin.com/hJ8EbnvD

I've tried it on my main server and then on a test server - on both servers there occurs the problem.
### Additional comments (optional)

**Comment by supercrafter333** [comment]
This is not a Bug in MyPlot. This Error/Crash comes if the Level/World not a worlds by MyPlot.

**Comment by EndermanLetsPlay** [comment]
The world has been generated with the MyPlot generator and only with the new version it doesn't work anymore.

**Comment by EndermanLetsPlay** [comment]
@jasonwynn10 @supercrafter333

**Comment by jasonwynn10** [comment]
The issue is that the world doesn't have a config for it. Make a config for it be be registered as a myplot world.

**Comment by EndermanLetsPlay** [comment]
Hi! It even doesn't work if I create a completely new world with "/p generate name".

Could you please help me out? I'd be very glad.

Best regards,
Giulio
