### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by benda95280** [jasonwynn10/MyPlot#393]
Link to crashdump: https://pastebin.com/EZHY6cqu

### Additional comments (optional)
My plugin has crashed just before, i'm okay with that, but MyPlot shouldn't crash ? :(

**Comment by ImDaRealAni** [comment]
Spoons not supported

https://github.com/jasonwynn10/MyPlot/issues/327#issuecomment-681889341

**Comment by benda95280** [comment]
Sur that's caused by it ?
Using it since 2 Weeks without trouble :/

**Comment by ImDaRealAni** [comment]
![image](https://user-images.githubusercontent.com/51390305/117497105-9b66bf00-af3d-11eb-8d57-a6e01c172dc4.png)

**Comment by ImDaRealAni** [comment]
https://github.com/jasonwynn10/MyPlot#note-myplot-is-designed-to-only-support-pmmps-version-of-the-pocketmine-mp-server-software-and-does-not-support-third-party-builds-any-changes-to-the-code-in-custom-installations-will-not-be-supported

**Comment by jasonwynn10** [comment]
One of your plugins is deleting the level object linked to the player class in the teleport event. This is not caused by myplot.

**Comment by benda95280** [comment]
Thanks for the tips, will take a look.
