### ISSUE TITLE
Users are unable to build on certain areas of merged plots

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#399]
Plot Merge is fine but you missing the roads people can not build on merged roads pls fix this 😀

But Good Job for Worked Merge :D

**Comment by DragonfireHD** [comment]
Oh 1 missing more Unmerg the Plot

**Comment by supercrafter333** [comment]
This is a knowing bug. But thanks for report.
Jason says that this is a bug by the database. Jason will fix the bug soon.

**Comment by DragonfireHD** [comment]
/p Dispose Bug Video is implemted for see the Problem

https://user-images.githubusercontent.com/50929188/119559775-c65d6980-bdab-11eb-9a46-7718632ad9d4.mp4

/p dispose confirm | Bug if you make the Plot free the /p dispose confirm give the Plot another Player this Plot please Fix

**Comment by supercrafter333** [comment]
That's a Bug by the Database.

**Comment by supercrafter333** [comment]
This is an important bug. Why it take so long to fix them? 😁
