### ISSUE TITLE
[Idea] Merge API

### ISSUE THREAD

**Issue by FlxiBoy1313** [jasonwynn10/MyPlot#405]
[Deuscht | German]
Hallo,

ich möchte gerne eine Idee zum Merge bringen. Das jemand eine API rein macht, ob zu checken ob das Plot gemerged ist oder nicht, weil **if ($plot->isMerged)** geht nicht mehr.

Wäre sehr Lieb.

[English | Englisch]
Hello,

i want to bring an idea to merge. That someone an API pure makes, whether to check whether the plot is merged or not, because **if ($plot->isMerged)** does not work.

Would be very nice

**Comment by supercrafter333** [comment]
That's a bug by the Database. Please don't use the acutall version. Wait a few days, Jason will make a version with new database saving, then will work `$plot->isMerged` again.

:)
