### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hazard165** [jasonwynn10/MyPlot#41]
Asynchronous Worker #1 thread/CRITICAL Error: "Call to undefined method pocketmine\level\format\Chunk::setBiomeColor()" (EXCEPTION) in "/MyPlot_v1.0.13 (2).phar/src/MyPlot/MyPlotGenerator" at line 124

**Comment by Aericio** [comment]
Please use the issue template.

**Comment by Aericio** [comment]
Maybe related to #43 ?

**Comment by jasonwynn10** [comment]
@Aericio Please don't bump old issues, this was already fixed

**Comment by Aericio** [comment]
Was it? Okay.
