### ISSUE TITLE
The selected data provider crashed. JSON will be used instead.

### ISSUE THREAD

**Issue by JustSxm** [jasonwynn10/MyPlot#415]
### Issue description
"selected data provider crashed" happens on load, I am certain my database details are correct since it works with libasynql.
 
- Expected result: What were you expecting to happen?
Use mysql
- Actual result: What actually happened?
crashed and used json

### Steps to reproduce the issue
1. 
2. ...

### OS and versions

* Plugin Version: 1.10.1 (also tried master branch)
* PocketMine-MP: 3.22.1+dev
* PHP: 7.4.18
* Game version: Win10

### Other Plugins
- If you remove all other plugins, does the issue still occur? Yes

I would assume the error happens because my password needs to be between double quotes since some characters occur an error in yaml_parse.

**Comment by JustSxm** [comment]
The errors comes from MySqlProvider:
```
if($this->db->connect_error !== ''){
throw new \RuntimeException("Failed to connect to the MySQL database: " . $this->db->connect_error);
}
```
$this->db->connect_error = NULL

**Comment by JustSxm** [comment]
This isnt the only fix

```$this->db->query("ALTER TABLE plots ADD COLUMN pvp INT AFTER biome;")```

Afterward fails.. even if the one prior did not

**Comment by JustSxm** [comment]
```$stmt = $this->db->prepare("INSERT INTO mergedPlots (`originId`, `mergedId`) VALUES (?,?) ON DUPLICATE KEY UPDATE originId = VALUES(originId), mergedId = VALUES(mergedId);");```
is the reason of the crash.

**Comment by HighTecDev** [comment]
How exactly do you think that this statement triggers a crash?
Error message?

**Comment by JustSxm** [comment]
When you look at the value it returns, it returns false meaning the query failed (because the table mergedPlots does not exist)

**Comment by BenasPaulikas** [comment]
I'm also experiencing this issue. I'm almost sure about mysql connection.

```
[17:11:01.419] [Server thread/INFO]: Loading MyPlot v2.1.2
[17:11:01.427] [Server thread/DEBUG]: [MyPlot] Loading Configs
[17:11:01.428] [Server thread/DEBUG]: [MyPlot] Loading MyPlot Generator
[17:11:01.431] [Server thread/DEBUG]: [MyPlot] Loading Languages
[17:11:01.431] [Server thread/DEBUG]: [MyPlot] Loading Data Provider settings
[17:11:01.436] [Server thread/ERROR]: [MyPlot] The selected data provider crashed. JSON will be used instead.
```

So I've tried executing first mysql statement manually and got error
```
mysql> CREATE TABLE IF NOT EXISTS plotsV2 (level TEXT, X INT, Z INT, name TEXT, owner TEXT, helpers TEXT, denied TEXT, biome TEXT, pvp INT, price FLOAT, PRIMARY KEY (level, X, Z));
```

```
ERROR 1170 (42000): BLOB/TEXT column 'level' used in key specification without a key length
```

Is it possible to enable more logging ? Currently I don't even know what's the issue but I see that table can't be created

**Comment by JustSxm** [comment]
No you're not experimenting the same error. Please look at the error you have, it says it all. My error was related to the queries the plugin does itself

**Comment by BenasPaulikas** [comment]
Excuse me moved to https://github.com/jasonwynn10/MyPlot/issues/479
