### ISSUE TITLE
Oops something went wrong (Message to /p dispose confirmar)

### ISSUE THREAD

**Issue by MrBlasyMSK** [jasonwynn10/MyPlot#418]
### Issue description
If you delete a parcel with the command of / p dispose confirm, it appears in Spanish "Ups something went wrong" but that message should only appear when something has not worked well, in this case if you delete the user's parcel, only the displayed text is wrong

- Expected result: That the message of dispose.success=La parcela se ha eliminado
- Actual result: That the message of error=Ups! Algo salió mal

### Steps to reproduce the issue
1. Buy a plot
2. Use /p dispose confirmar
3. Message appears

### OS and versions

* Plugin Version: Dev731
* PocketMine-MP: 3.22.0
* PHP: 7.4
* Game version: Win10

### Other Plugins
Some plugins are private

- If you remove all other plugins, does the issue still occur? I didnt test it because i dont have more servers
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by jasonwynn10** [comment]
Is this issue still present with the latest build?

**Comment by MrBlasyMSK** [comment]
Fix issue #423 because Myplot won't load and I can't test it
@jasonwynn10

**Comment by MrBlasyMSK** [comment]
Still happening in version 751
@jasonwynn10

**Comment by jasonwynn10** [comment]
Does the command sender had the admin permission for dispose?

**Comment by MrBlasyMSK** [comment]
> Does the command sender had the admin permission for dispose?

Yes i got op
