### ISSUE TITLE
[Bug] MyPlot error crash the start

### ISSUE THREAD

**Issue by FlxiBoy1313** [jasonwynn10/MyPlot#423]
### Issue description

(sry my english is bad, google translator helped a little)

- The MyPlot starts without any problems.
- I created the server and then this error came up. I also don't have a world of MyPlot where is weird.

### Steps to reproduce the issue
1. I don't know, but I would be happy if that happens.

### OS and versions
* Plugin Version: v.2.0.1
* PocketMine-MP: 3.22.1
* PHP: 7,4
* Game version: PE/Win10

### Other Plugins
MyPlot, DevTools, BuilderTools, FormAPI, Multiworld, EconomyAPI and MyPlugin

- If you remove all other plugins, does the issue still occur? **Yes**
- Can you provide sample, *minimal* reproducing code for the issue? **No sorry**

### Console error, backtrace or other files
![image](https://user-images.githubusercontent.com/65186341/129473684-e39944be-db37-4cf3-85a5-d9e3feea35c2.png)
![image](https://user-images.githubusercontent.com/65186341/129474230-27697932-392a-4f04-b0aa-967e6a6dd866.png)

**Comment by jasonwynn10** [comment]
Not enough information. Please upload the whole crashdump file from where it says in the red error message.

**Comment by FlxiBoy1313** [comment]
Okay, here:
[Sun_Aug_15-10.20.07-BST_2021.log](https://github.com/jasonwynn10/MyPlot/files/6988147/Sun_Aug_15-10.20.07-BST_2021.log)
