### ISSUE TITLE
Plots owners removed Dev748

### ISSUE THREAD

**Issue by MrBlasyMSK** [jasonwynn10/MyPlot#426]
### Issue description
The database does not load the names of the players in the plots and all the plots appear to be purchased

- Expected result: What were you expecting to happen? That the plots that are already purchased could not be bought and the name of the owner would appear on the plot
- Actual result: What actually happened? What i said above

### Steps to reproduce the issue
1. Use dev 748
2. See the bug

### OS and versions

* Plugin Version: dev748
* PocketMine-MP: 3.22.1
* PHP: 7.4
* Game version: Win10

### Other Plugins

- If you remove all other plugins, does the issue still occur? Yes/No (delete as appropriate) I can't test it because I don't have another server
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

### Console error, backtrace or other files
No error

**Comment by jasonwynn10** [comment]
Please post a copy of your plot db file for reference.

**Comment by MrBlasyMSK** [comment]
I explain:

The latest version is bug, when I go to plots the name of the players does not appear and it appears to buy the plots

But if you put the old version 731 if it works correctly

**Comment by jasonwynn10** [comment]
Please post a copy of your plot db file for reference.

**Comment by MrBlasyMSK** [comment]
[Plots.zip](https://github.com/jasonwynn10/MyPlot/files/6988318/Plots.zip)

**Comment by jasonwynn10** [comment]
It looks like the conversion from teh v1 to the v2 table isnt working correctly 🤔 
![image](https://user-images.githubusercontent.com/16521025/129482531-456fad0f-8ce7-47da-b23e-63acc7ab39bb.png)

**Comment by jasonwynn10** [comment]
The query works as intended though so it must be a logic error detecting if the v1 table exists
![image](https://user-images.githubusercontent.com/16521025/129482586-e924cc94-2f12-4708-9ef1-8a310dd40ce5.png)

**Comment by MrBlasyMSK** [comment]
I just hope you don't tell me that I have to delete the database :)
