### ISSUE TITLE
"Could not load plugin 'MyPlot': Incompatible API version"

### ISSUE THREAD

**Issue by infinity-pe** [jasonwynn10/MyPlot#44]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
[Server] Server thread/ERROR Could not load plugin 'MyPlot': Incompatible API version

## Reproducing the issue
I get this error message, the plugin cannot load. If it says _Incompatible API version_, it means I need to update the plugin(?) What can I do to fix this?

## Client information
PocketMine-MP Version: 1.0dev (API 3.0)
Plugin Version: I don't know
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
I need more information before I can fix this

**Comment by Aericio** [comment]
Use https://github.com/jasonwynn10/MyPlot/tree/API3

**Comment by infinity-pe** [comment]
@Aericio Thank you so much! It works now.
But I always get the error:
_`Server thread/CRITICAL Error: "Call to a member function bindValue() on boolean" (EXCEPTION) in "/MyPlot.phar/src/MyPlot/provider/SQLiteDataProvider" at line 115`_
