### ISSUE TITLE
/p reset\dispose bug with merge plots

### ISSUE THREAD

**Issue by efor89** [jasonwynn10/MyPlot#448]
### Issue description

hi jason i have the problem that only 1 plot is remove from the max plots if the plot is a merge.
if my max plots is 4 and i have a 4er merge and i use reset after this i can only claim 1 plot.

### Steps to reproduce the issue
1. /p claim
2. /p merge confirm
3. /p reset confirm
4. /p list
5. /p claim

### OS and versions
* Plugin Version: dev 763
* PocketMine-MP: 1.17.3
* PHP: 7.4
* Game version: Win10

### Other Plugins
- multiworld
- purechat
- pureperms
- worldprotect
- worldguard
- slapper
- skinfixpm
- invcrashfix
- formapi
- devirion
- economyapi

### Console error, backtrace or other files
no error

**Comment by MonoAdrian23** [comment]
Why you create 2 Same Issues?

**Comment by HighTecDev** [comment]
A Merge always counts as one Plot

**Comment by efor89** [comment]
no a 4er merge are 4 plots

**Comment by Wertzui123** [comment]
Should a merge count as one or multiple plots? @jasonwynn10
