### ISSUE TITLE
CityBuild Road Bug Players Build on Road with No Permission 

### ISSUE THREAD

**Issue by DragonfireHD** [jasonwynn10/MyPlot#449]
### Issue description

- Expected result: It is not good for random player to build a Random Road with blocks Griefing is Coming with that Problem.

### Steps to reproduce the issue
1. ... player go to the Road 
2. ... player on the Road placed a random Block on the Road

### OS and versions

* Plugin Version: 2.1.0
* PocketMine-MP: 3.22.1
* PHP: 7.4.13
* Game version: PE/Win10

### Other Plugins

- If you remove all other plugins, does the issue still occur? No MyPlot cant be remove but i need it aktiv

  - Have you asked for help in the community discord before creating an issue? 
  - Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.
  - Player with no permission's can build on the Plot Rosds
  - i looked for where the bug comes i dont found this.

### Console error, backtrace or other files
 No errors

**Comment by DragonfireHD** [comment]
Yellow Bug Area with Road Build Bug player can build on the Road 
Red Main Plot Area 



![Screenshot_20211010-174218_Minecraft](https://user-images.githubusercontent.com/50929188/136703309-3cc21b66-d9cd-48a7-a3f6-d21cf36dd31c.png)



![Screenshot_20211010-174813_Discord](https://user-images.githubusercontent.com/50929188/136703298-af99280a-12f6-4d7f-9b9e-64a7ab83e6a8.png)

**Comment by Wertzui123** [comment]
I can confirm this.

**Comment by DragonfireHD** [comment]
Fixed
