### ISSUE TITLE
SQLite error on startup

### ISSUE THREAD

**Issue by infinity-pe** [jasonwynn10/MyPlot#45]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
The commands `/p claim` `/p reset` `/p dispose` etc. don't work: "_An unknown error occured..._"
Error messages on console.

## Reproducing the issue
1. Start Server
2. Going into the Plots World

## Client information
PocketMine-MP Version: 1.6.2dev-#61
API: 3.0.0
Plugin Version: unknown
PHP version: 7.0.13 (default)

## Optional information
`Server thread/CRITICAL Error: "Call to a member function bindValue() on boolean" (EXCEPTION) in "/MyPlot.phar/src/MyPlot/provider/SQLiteDataProvider" at line 115`

**Comment by Aericio** [comment]
Unable to reproduce.

**Comment by infinity-pe** [comment]
@Aericio 
What shall I do? It always gives me that error.

**Comment by jasonwynn10** [comment]
We can't fix it if we can't reproduce the error. I recommend reinstalling the plugin and deleting its files. Also, I changed the title for a reason -_-

**Comment by jasonwynn10** [comment]
Also, you didn't give the plugin version hash, so we don't have a way of knowing whether or not you are even updated

**Comment by infinity-pe** [comment]
Does it mean that I also need to delete Plots World? And the config.yml too?

**Comment by infinity-pe** [comment]
OK, here: This server is running PocketMine-MP 1.6.2dev-#61 Unleashed implementing API version 3.0.0-ALPHA1 for Minecraft: PE v1.0.0.16 (protocol version 100)

**Comment by infinity-pe** [comment]
@jasonwynn10 
OK, the plugin version is: 1.1.3

**Comment by jasonwynn10** [comment]
Unfortunately that isn't helpful. I need the git hash of the plugin version, not the version from the plugin.yml

**Comment by infinity-pe** [comment]
Now it says:
`09.02 16:31:52 [Server] Server thread/CRITICAL DivisionByZeroError: "Modulo by zero" (EXCEPTION) in "/MyPlot.phar/src/MyPlot/MyPlot" at line 180
09.02 16:31:52 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'MyPlot v1.1.0': Modulo by zero on MyPlot\EventListener
09.02 16:31:52 [Server] INFO Warning: Division by zero in phar:///plugins/MyPlot.phar/src/MyPlot/MyPlot.php on line 179`

**Comment by jasonwynn10** [comment]
something tells me that you didnt read the README...

**Comment by infinity-pe** [comment]
@jasonwynn10 

> _Please note that the API3 Branch is currently under heavy development for the new changes in pmmp 1.0 and may not work 100% of the time. _

Is that the reason? If yes, what can I do now?

**Comment by jasonwynn10** [comment]
The API3 branch is currently in a fully working state, so that isn't the issue. I believe that you aren't using the latest version that includes the fixes

**Comment by infinity-pe** [comment]
@jasonwynn10 
Where can I find the newest version? On API3 Branch or...?

**Comment by jasonwynn10** [comment]
https://poggit.pmmp.io/r/1521/MyPlot.phar

**Comment by infinity-pe** [comment]
@jasonwynn10 
Thank you so much! It works perfectly!
