### ISSUE TITLE
Request - AUTO CLAIM next available PLOT

### ISSUE THREAD

**Issue by Starflux** [jasonwynn10/MyPlot#46]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue Description
unable to AUTO CLAIM the next available plot, within players plot limit.

## Reproducing the issue
1. As there is no auto claim command the player must move to the plot and claim manually using /p claim.

## Client information
PocketMine-MP Version: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
Plugin Version: Dev build #27
PHP version: 7.0.15

## Optional information
i am trying to implement this plugin on my home server so that the kids do not have to put commands into chat.

I am almost there, i can do most of this with the plugin taptodo.

i would like to ask for command line function to do the following:

/p auto (change to spawn player in center of the next available plot) 

this would allow me to use both /p auto and /p claim with the taptodo plugin on a sign.

AND

/ give (the next available auto plot, plot limit override as OP command) - at the minute i can do this manually but i dont know the next plot by number and would prefer not.

**Comment by jasonwynn10** [comment]
This is already being worked on. Use the CustomizableCommands branch for the requested feature

**Comment by Starflux** [comment]
Thankyou for working on this, it is greatly appreciated.

I have just installed the CustomizableCommands branch (MyPlot v1.1.3) and enabled:

1. Auto Center Only

- AutoCenter: true #Makes players teleport to the **bottom left** of the plot
- I then maually ran the /p claim which worked
- When i attempted to run /p auto a second time
- display said i was at plot 0,1 when i was in fact physically still at 0,0
- as i already owned the plot i was unable to claim the next plot
 
2. Auto Center and Auto Claim

- i rebuilt my installation fresh and installed the plugin and this time ran both commands as true:
    AutoCenter: true #Makes players teleport to the center of the plot
    AutoClaim: true #Allows instant plot claiming after being teleported
-  When i run /p auto now i spawn in the original road spwan of the plot.

I understand this is Work In Progress and look forward to testing your future realeases.

**Comment by jasonwynn10** [comment]
Thank you for all the feedback! This will help so much in error solving

**Comment by Starflux** [comment]
thanks for taking a look, just ran this up on test again.

**the following is still present**

**Auto Center Only**
AutoCenter: true #Makes players teleport to the bottom left of the plot

- I then maually ran the /p claim which worked
- When i attempted to run /p auto a second time
- display said i was at plot 0,1 when i was in fact physically still at 0,0
- as i already owned the plot i was unable to claim the next plot

Error shown in Console:
NONE

**however... a slight change with this next test**

**Auto Center and Auto Claim**
i rebuilt my installation fresh and installed the plugin and this time ran both commands as true:
AutoCenter: true #Makes players teleport to the center of the plot
AutoClaim: true #Allows instant plot claiming after being teleported

- When i run /p auto for the first time i spawn in the bottom left of the plot (0,0) and the plot **IS** claimed automatically.
- the problem is with the /auto command **not** physically moving to the next plot this is causing problems as when the command is run a second time, display said i was at plot 0,1 and **failed to claim the plot**, when i checked i was in fact physically still at 0,0

Error in console:
Notice: Undefined offset: 0 in phar://C:/Users/steve/Desktop/PocketMine-Workbench/plugins/phar_MyPlot-CustomizableCommands_rep6eUMCW2hzoaf.phar/src/MyPlot/subcommand/AutoSubCommand.php on line 37

i accept this is low priority and really do appreciate the time you have invested in this already.

Kind Regards
Star

**Comment by Starflux** [comment]
i can confirm it is working
AutoCenter: true #Makes players teleport to the center of the plot
/auto moves to next available plot

AutoCenter: true #Makes players teleport to the center of the plot
AutoClaim: true #Allows instant plot claiming after being teleported
/auto moves to next available plot and claims it

Note: tested with OP and NON OP, works as expected

OP claimed as many as i liked (10 in this case)

NON OP was limited to 2 plots

Thankyou for sorting this out it will make a big difference allowing servers to run without the need to manipulate chat commands.

my kids are under 5 so i do not expect them to put commands in

your a legend!
