### ISSUE TITLE
Server crashed with the new API 4 version

### ISSUE THREAD

**Issue by Giulizo** [jasonwynn10/MyPlot#466]
The file is named differently because permissions had to be set to "op" in plugin.yml. Nothing was changed in the source code.

This is the link to the crash stack trace:
https://mcpaste.io/3f1671379567cfcc

**Comment by PocketMiner92** [comment]
Use another Plot Plugin.
Myplot is really shit

**Comment by provsalt** [comment]
> Use another Plot Plugin.
> Myplot is really shit
> 

You should contribute if it's shit. That's what pull requests are for.

**Comment by PocketMiner92** [comment]
Also i should rewrite Myplot?
Because the complete Code is Shit.

**Comment by PocketMiner92** [comment]
supercrafter333 say it too.
This is why CPlot exist

**Comment by ethaniccc** [comment]
"The complete code is shit"

Dude, you literally made a **file** called `src` in one of your repositories instead of a directory. If you're gonna call it "shit" and say you're going to rewrite it - at least be able to back it up 😭

**Comment by jasonw4331** [comment]
what's the release version you're using?
