### ISSUE TITLE
/p does not show the UI interface

### ISSUE THREAD

**Issue by MrBlasyMSK** [jasonwynn10/MyPlot#469]
### Issue description

- Expected result: Use /p to display the UI interface
- Actual result: Displays the list of commands on page 1.

### Steps to reproduce the issue
1. Use /p
2. See the error

### OS and versions

* Plugin Version: dev805
* PocketMine-MP: 4.2.3
* PHP: 8.0.16
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Other Plugins

Plugins (14): BedrockEconomy v2.0.7, BuilderTools v1.4.0-dev, DevTools v1.15.0, FormAPI v2.1.0, KygekPingTPS v2.0.0, MultiWorld v1.7.0-beta4, MyPlot v2.1.0, PureChat v2.0.1, PurePerms v2.0.2, PurePermsScore v2.0.0, RedstoneCircuit v3.0.3, ScoreHud v7.0.0, SimpleNPC v3.0.1, Worlds v3.1.0

- If you remove all other plugins, does the issue still occur? I cannot test
- If the issue is **not** reproducible without other plugins:
  - Have you asked for help in the community discord before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by jasonw4331** [comment]
see what error? It works for me

**Comment by MrBlasyMSK** [comment]
> see what error? It works for me

https://streamable.com/xbchnz
