### ISSUE TITLE
/p info Won't Work

### ISSUE THREAD

**Issue by Dblcut3** [jasonwynn10/MyPlot#47]
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue Description
So, I replaced the new plots.db with my old plots.db so my players could keep their old plots still. Well, after I replaced the files, I can no longer do /p info. It just says an unknown error has occurred. The message on the bottom of the screen saying the plot coordinates and how to claim is also no longer here.

## Reproducing the issue
1. Replace plots.db with an old plots.db (possibly from original MyPlot plugin)
2. Type /p info

## Client information
PocketMine-MP Version: f5e39ea
Plugin Version: 4bb874e
PHP version: 7.0.13

**Comment by Dblcut3** [comment]
Also, I just realized, /p home gives a "you don't own any plots" message unless you are in the world your plots are in.

**Comment by jasonwynn10** [comment]
I still have yet to implement an auto-updater for the databases. That is also being worked on at the moment

**Comment by jasonwynn10** [comment]
related to #45 #16 and #26

**Comment by Dblcut3** [comment]
By the way, I think the same issue is happening with /p addhelper

And I apologize for my lack of knowledge on all this, but how do I find the git hash I am using?

**Comment by jasonwynn10** [comment]
First off, what branch are you using and are you running the latest version of the plugin?

**Comment by Dblcut3** [comment]
I just installed it today and yes I am using the API3 branch.

I'm also having issues with non ops claiming plots. Not sure if it's related to this issue or not.

**Comment by thebigsmileXD** [comment]
What exactly are the database changes? I plan using this fork, the Mwvent fork segfaults. 
Can i simply use the old mysql table?
![image](https://user-images.githubusercontent.com/8733998/28013558-bab6b17a-6569-11e7-821d-8b12563c13e5.png)
