### ISSUE TITLE
/p home Only works in the world your plot is in

### ISSUE THREAD

**Issue by Dblcut3** [jasonwynn10/MyPlot#48]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

When you type /p home it says you do not own any plots. This is fixed if you go into the plot world your plots is in. But, this issue doesn't allow people to tp to their plots from spawn.

## Reproducing the issue
1. Type /p home outside of a plot world

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
I will add this feature on the CustomizableCommands branch soon

**Comment by Dblcut3** [comment]
So at the moment, there is no way around this?

**Comment by jasonwynn10** [comment]
not yet

**Comment by jasonwynn10** [comment]
Actually, by adding this feature, the plugin loses the ability to have more than one plot world. What is the preference?

**Comment by Aericio** [comment]
@jasonwynn10 Check gitter.im please. (delete this if you seen)

**Comment by jasonwynn10** [comment]
bump @Dblcut3

**Comment by Aericio** [comment]
you could make like `/p home (worldname) (number)`?
