### ISSUE TITLE
Server crash on /p clear

### ISSUE THREAD

**Issue by justin-eckenweber** [jasonwynn10/MyPlot#488]
Sometimes the server crashes when someone executes /p clear.
https://pastebin.com/GwTvp9tm

**Comment by MonoAdrian23** [comment]
Use CPlot

**Comment by MCPEAbdu77** [comment]
> Use CPlot

L comment

**Comment by justin-eckenweber** [comment]
> Use CPlot

Don't comment things that don't help.

**Comment by ColinHDev** [comment]
It looks like you are using an old version of MyPlot . This error got fixed two months ago: cc5b2f81817166c89bd62a5761daaf9f480ececf

**Comment by justin-eckenweber** [comment]
> It looks like you are using an old version of MyPlot . This error got fixed two months ago: [cc5b2f8](https://github.com/jasonwynn10/MyPlot/commit/cc5b2f81817166c89bd62a5761daaf9f480ececf)

Ah yeah! It just wasn't updated on poggit.
