### ISSUE TITLE
Question about generators

### ISSUE THREAD

**Issue by Dblcut3** [jasonwynn10/MyPlot#49]
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

Hi. Sorry if this is the wrong place to ask this but I don't know where else to. Is there a way to have the old API version of the plugin with the new generator on the API 3 branch? I have been using the old API plugin branch but with already generated worlds, but it would be much nicer if I could get the new generator on the old API version. Is there any easy way to do this? (API3 branch isnt really working to my liking) If it's not possible, just close this thread.

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
what are u meaning by the old API version?

**Comment by Dblcut3** [comment]
The version that is not API3. Im asking if theres a way to put the new API3 terrain generator on that version. If its not possible sorry for wasting time lol.

**Comment by jasonwynn10** [comment]
there shouldn't be any differences between the generators

**Comment by Dblcut3** [comment]
One generates on Anvil format the other doesnt is what I believe it is.

**Comment by jasonwynn10** [comment]
That isn't anything to do with the plugin. That is set in the pocketmine.yml file

**Comment by Dblcut3** [comment]
Are you sure? All worlds generate on the new format except for when I use /p generate. (It just brings you to the void) If I use the API3 version of this plugin, it works fine, but there are too many issues with that version right now for me to use it.

**Comment by jasonwynn10** [comment]
The generator on the master branch if left for PocketMine-MP 2.1.0 API. It won't work with API3

**Comment by Aericio** [comment]
Next time, ask questions on https://gitter.im/MyPlot/Lobby ;)
