### ISSUE TITLE
Latest build of PocketMine-MP causes error in console for MyPlot API3 plugin

### ISSUE THREAD

**Issue by NML32** [jasonwynn10/MyPlot#53]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Error in console when loading MyPlot plugin on lates PM build.

## Reproducing the issue
1. Running the latest PM build start server with MyPlot API3 plugin
2. ...

## Client information
PocketMine-MP Version:  PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.3.0 (protocol version 101)
Plugin Version:  MyPlot v1.1.3
PHP version: 7.0.13 (default)

## Optional information
```
Warning: syntax error, unexpected '&' in phar://C:\Users\Mark\Desktop\PocketMine - 1.0 - Alpha3\plugins\MyPlot_1_Plot_Default.phar/resources/eng.ini on line 2
 in phar://C:/Users/Mark/Desktop/PocketMine - 1.0 - Alpha3/PocketMine-MP.phar/src/pocketmine/lang/BaseLang.php on line 85
```

**Comment by jasonwynn10** [comment]
I believe this is because dktapps changed how pocketmine does it's ini parsing

**Comment by TanToan99** [comment]
use lang.yml for language and update command system to fix the issues

**Comment by jasonwynn10** [comment]
This issue should be fixed in the most recent commit
