### ISSUE TITLE
Water Blocked

### ISSUE THREAD

**Issue by MrJhon2** [jasonwynn10/MyPlot#54]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Liquids don't work in plots

## Reproducing the issue
1. Place Water or Lava in a plot world

## Client information
PocketMine-MP Version: N/A
Plugin Version: Unknown
PHP version: 7.0.13 (default)

## Optional information
None

**Comment by jasonwynn10** [comment]
In the config is a setting to enable block updates. That should fix your problem.

**Comment by MrJhon2** [comment]
How can I be solving this? Can you give me details of how I can be activating lava and water at all

**Comment by jasonwynn10** [comment]
As was previously stated, there is a setting in the config file to enable block updates. That will fix your problem.

**Comment by Aericio** [comment]
Again, the reason why water flow has been disabled is because if it could flow, it could flow into the paths and other people's plots. If you don't care, I guess removing that block of code would let it flow.

**Comment by thelucyclub** [comment]
Isn't it possible to just not tick the water? It would lagg the server anyways.

**Comment by jasonwynn10** [comment]
I don't think it's possible to prevent a block from being ticked

**Comment by thelucyclub** [comment]
Fair enough.

**Comment by thebigsmileXD** [comment]
```


    public function onBlockUpdate(BlockUpdateEvent $event) {
        /*
         * Disables water and lava flow as a temporary solution.
         */

        $levelName = $event->getBlock()->getLevel()->getName();
        if ($this->plugin->isLevelLoaded($levelName)) {
            $event->setCancelled(true);
        }
        if ($event->getBlock() instanceof Water or $event->getBlock() instanceof Lava && is_null($this->plugin->getPlotByPosition($event->getBlock()))) {
            $event->setCancelled(true);
        }
    }
```
I once added this onplot check, it disables it on the roads

**Comment by jasonwynn10** [comment]
@thebigsmileXD the issue is water spreading. Even if the water isn't in the road, it can still spread to it.

**Comment by thebigsmileXD** [comment]
I used that code snipped since about 2 years now, and never saw water spreading over borders, simply on plots.

**Comment by jasonwynn10** [comment]
I suppose that makes sense because it's in the BlockUpdateEvent function instead of a BlockPlaceEvent function
