### ISSUE TITLE
We need a command for list helpers in one plot

### ISSUE THREAD

**Issue by RocoWayne** [jasonwynn10/MyPlot#57]
We need a command like /p listhelpers , so we can see what users we have in a plot, so we can remove them or add another.

**Comment by ealgueiroqb9** [comment]
That would come in handy :)

**Comment by Aericio** [comment]
Doesn't `/p info` show helpers already?

**Comment by RocoWayne** [comment]
@Aericio  yes, i didint know that ... but also is a handy command /p listhelpers
