### ISSUE TITLE
Map generation error

### ISSUE THREAD

**Issue by MattTardis** [jasonwynn10/MyPlot#6]
After the server is restarted, the map will be wrong.
![screenshot_2016-08-05-15-46-36_com mojang minecraftpe](https://cloud.githubusercontent.com/assets/20631103/17430003/7ac96fc6-5b24-11e6-8f30-2692c49490da.png)

**Comment by jasonwynn10** [comment]
working on a fix currently

**Comment by Dog2puppy** [comment]
That's just a bug where it shows chunks from the old world that haven't unloaded. Just fly around a little and it'll be fine.

**Comment by jasonwynn10** [comment]
If the bug can be fixed by a restart or flying around, then there is no need for a patch

**Comment by Aericio** [comment]
Server core issue, not loading chunks fast enough.
