### ISSUE TITLE
Pocketmine CRASH

### ISSUE THREAD

**Issue by NiclasQueen** [jasonwynn10/MyPlot#62]
[Server thread/CRITICAL]: ClassNotFoundException: "Class spoondetector\SpoonDetector not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Aericio** [comment]
How do you reproduce the issue?

**Comment by jasonwynn10** [comment]
He isn't using the poggit build

**Comment by Aericio** [comment]
@NiclasQueen Try downloading the latest phar [here.](https://poggit.pmmp.io/ci/jasonwynn10/MyPlot/MyPlot)
