### ISSUE TITLE
Limiting plots

### ISSUE THREAD

**Issue by Kyrobi** [jasonwynn10/MyPlot#67]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

The permission node to limiting amount of plots player can claim does not work.

Try to use the permission node - -plot.claimplots.2 in pureperms, it doesn't deny a player from claiming 2 plots.

**Comment by jasonwynn10** [comment]
This is an issue with PurePerms, not MyPlot
