### ISSUE TITLE
Could the plugin get updated to API 3 Alpha6?

### ISSUE THREAD

**Issue by NML32** [jasonwynn10/MyPlot#68]
Could the plugin get updated to API 3 Alpha6?

**Comment by TDMidkwhatisxd** [comment]
This plugin wont work with api3/block branch from pmmp. I will try to fix for myself.

**Comment by jasonwynn10** [comment]
@TDMidkwhatisxd api3/blocks is alpha7

**Comment by jasonwynn10** [comment]
fixed in 7be3847a12d6f01d4431aedfff1365a959362902

**Comment by Driesboy** [comment]
support for aphpa7???

**Comment by jasonwynn10** [comment]
@Driesboy I will support that when it is on the master branch of PMMP

**Comment by Driesboy** [comment]
k

**Comment by Driesboy** [comment]
beta branch maybe???

**Comment by jasonwynn10** [comment]
@Driesboy API3 is already a beta branch. Support for more is more work than I am willing to put in.

**Comment by NML32** [comment]
Dang, PMMP Alpha7 is already out.

**Comment by jasonwynn10** [comment]
Yup, now I need to make MyPlot compatible

**Comment by thebigsmileXD** [comment]
@jasonwynn10 want me to take some work off your shoulders? I got plenty of time

**Comment by jasonwynn10** [comment]
Feel free, I'm not able to do any work for the next few days anyway while I'm on vacation in the mountains.

**Comment by Driesboy** [comment]
Same i am in austria

**Comment by HimbeersaftLP** [comment]
> Same i am in austria

Enjoy your stay lol
