### ISSUE TITLE
SpoonDetector first run and another error

### ISSUE THREAD

**Issue by SalmonDE** [jasonwynn10/MyPlot#69]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
This is a pretty hidden and awkward one. When the plugin is run for the first time and the plugin folder has not been created yet and a spoon was detected, [this line](https://github.com/Falkirks/spoondetector/blob/642b8f8a08e64c0ee5166fe132aed9c241c69b37/src/spoondetector/SpoonDetector.php#L48) will result in true.

But the problem now is that on [the next line](https://github.com/Falkirks/spoondetector/blob/642b8f8a08e64c0ee5166fe132aed9c241c69b37/src/spoondetector/SpoonDetector.php#L49) the spoon detection tries to open a file in a non-existing directory which results in an error.

I tested this with an edited pmmp version which returns "Spoon" as it's name:
![image](https://user-images.githubusercontent.com/15953947/27612898-009042cc-5b99-11e7-9392-2bbee51f746b.png)

## Reproducing the issue
1. Setup a server which doesn't return "PocketMine-MP" in [Server->getName()](https://github.com/pmmp/PocketMine-MP/blob/ae612b913ebdf6fad65dfe270c20300720265a64/src/pocketmine/Server.php#L271).
2. Make sure the MyPlot plugin folder isn't created yet
3. Run the server with a MyPlot version using the spoon detection class
4. Watch out for errors in the console

## Optional information
This could be fixed by creating the MyPlot directory before checking if the server is running a spoon or by requesting the creation of the plugin folder on the SpoonDetection repository.

I believe this should be fixed because spoon users won't see the disclaimer otherwise, but instead an error and the disabling of the plugin. That could lead to unnecessary issue reports.

**Comment by SalmonDE** [comment]
The other error which I didn't include up there is that if a spoon was detected and the plugin folder is present, the plugin would continue inside it's onEnable() function without checking if the plugin is disabled or not.
This results into this:
![image](https://user-images.githubusercontent.com/15953947/27613207-a3955f56-5b9a-11e7-9a0a-b67f3df0b426.png)

**Comment by jasonwynn10** [comment]
I believe this is an issue with the SpoonDetector virion.

**Comment by thebigsmileXD** [comment]
[10:25:48] [Server thread/CRITICAL]: ClassNotFoundException: "Class spoondetector\SpoonDetector not found" (EXCEPTION) in "src/spl/BaseClassLoader" at line 144
