### ISSUE TITLE
get_result on boolean

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#77]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
On any command, i get this:
![image](https://user-images.githubusercontent.com/8733998/28016602-67795d6c-6575-11e7-92dc-dd999dbc2ebb.png)
Also, all plots seem to be unclaimed.
![image](https://user-images.githubusercontent.com/8733998/28016731-06448a70-6576-11e7-9c90-57545bf5671a.png)

## Reproducing the issue
1. set up a myplot world
2. p claim

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

## Optional information
It simply looks like the "prepare" statements are all wrong. I never saw variables bound via `:name`
http://php.net/manual/de/mysqli.prepare.php

**Comment by thebigsmileXD** [comment]
I see the actual issue here. MySQL used on MySQLi database connection

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/MyPlot/commits/API3

I actually created a fork, and fixed the provider including fully correct SQL statements (theres no UPDATE OR REPLACE INTO in MYSQLi),
and proper use of the prepare statement.
But i removed the spoon check. You might like the latest commit though, i guess you know how to clone over a commit by another repo/fork.

**Comment by jasonwynn10** [comment]
fixed in b6505e037d28e1735a57bbdee2921c8650e95905
