### ISSUE TITLE
Error when issueing /p auto whilest using json provider

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#80]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Already made a PR to fix this, but here we go:
When using the JSON provider, executing /p auto leads into an error that states that no return value is given, causing the command to fail instead of notifying the player/commandsender that the command is not valid/beta/not finished yet.

## Reproducing the issue
1. Choose JSON Provider
2. issue /p auto

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
This issue is invalid because the Json and YAML providers are incomplete.
