### ISSUE TITLE
MySQLServer went away

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#84]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Reproducing the issue
1. run MySQL. Windows still has bugs that it disconnects. if "went away" appears, it should use the cache, and later try to reconnect

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

## Optional information
![image](https://user-images.githubusercontent.com/8733998/28163191-616f31f6-67ca-11e7-9e93-47cda6492f58.png)

**Comment by jasonwynn10** [comment]
Feel free ti fix it yourself. I don't do MySQL
