### ISSUE TITLE
MySQL Provider - Plots don't save

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#85]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Plots do not save.
Use /plot claim, /plot name or add/remove/sethelper, it returns "Something went wrong" in the chat

in /p list or /p homes the plot will not be shown
After a restart you will not have the plots.

## Reproducing the issue
1. Use MySQL provider since the commit that moved the querys out
2. Do anything mentioned above

## Client information
PocketMine-MP Version: -
Plugin Version: -
PHP version: 7.0.13 (default)

**Comment by jasonwynn10** [comment]
Why would making the queries variables cause this error??

**Comment by thebigsmileXD** [comment]
IT was invalid syntax

**Comment by thebigsmileXD** [comment]
https://github.com/jasonwynn10/MyPlot/issues/87
