### ISSUE TITLE
MyPlot Red.

### ISSUE THREAD

**Issue by xXNiceAssassinlo** [jasonwynn10/MyPlot#88]
Hey Developer of MyPlot can you help me plugin not working it get red like §cMyPlot 1.1.4

**Comment by jasonwynn10** [comment]
It sounds like you are not using PMMP or are using an outdated api

**Comment by xXNiceAssassinlo** [comment]
Ok I'll check

**Comment by xXNiceAssassinlo** [comment]
Here is version`This server is running Tesseract 1.3.0-Dev [Unity] implementing API Version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)`

**Comment by jasonwynn10** [comment]
MyPlot doesn't support third party versions of PocketMine-MP software. download the latest version of MyPlot from poggit at https://poggit.pmmp.io/ci/jasonwynn10/MyPlot/~
After restarting the server, edit the spoon detector file accordingly.
