### ISSUE TITLE
Option to disable "loaded from cache" spam

### ISSUE THREAD

**Issue by thebigsmileXD** [jasonwynn10/MyPlot#89]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
I just wondered why my server.log is so big.
50% of the file:
![image](https://user-images.githubusercontent.com/8733998/28482513-00b521cc-6e69-11e7-8352-5be2af75c3a5.png)

Total filesize: 8.5GB

There should be an option to disable it.. Debug should only be used for important stuff like issues.

## Reproducing the issue
1. Run a big server
2. Enable debug level 2 because you need to debug other plugins

## Client information
PocketMine-MP Version: 
Plugin Version: 
PHP version: 7.0.13 (default)

## Optional information
Option like option-log or so

**Comment by jasonwynn10** [comment]
If you are debugging other plugins, they should be running separately anyway.

**Comment by thebigsmileXD** [comment]
But per player onmove 1 spam log?
