### ISSUE TITLE
API-ALPHA8

### ISSUE THREAD

**Issue by optimusprime338** [jasonwynn10/MyPlot#98]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
```  
[Server thread/CRITICAL]: Error: "Class 'spoondetector\SpoonDetector' not found" (EXCEPTION) in "MyPlot-API3/src/MyPlot/MyPlot" at line 441

```

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 1.7dev-47 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.1.0.55
Plugin Version: latest API3 branch
PHP version: 7.2

**Comment by jasonwynn10** [comment]
Use the plugin builds from Poggit
https://poggit.pmmp.io/ci/jasonwynn10/MyPlot
