### ISSUE TITLE
Extension sqlite3 not loaded

### ISSUE THREAD

**Issue by CrazyCraft22** [jasonwynn10/MyPlot#99]
Hello, I wanted to report that the plugin does not load when I start the server, I am using the version of Pocketmine 1.7 dev-75 that uses the 3.0.0-ALPHA8 API, the plugin checks it and everything is fine, until the API is not which is not loaded by the API but does not recognize the extension sqlite3, will be the Pocketmine or Plugin? I await your answer. Greetings.

**Comment by NML32** [comment]
I'm seeing the same error.

[11:07:46] [Server thread/ERROR]: Required extension sqlite3 not loaded
[11:07:46] [Server thread/CRITICAL]: Could not load plugin 'MyPlot'

running PocketMine-MP 1.7dev-75 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.2.0.81 (protocol version 137)

**Comment by thebigsmileXD** [comment]
bin/php/php.ini: remove the `;` before extension = sqlite
